// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRiotMessagingServiceV1EntitlementsReader is a Reader for the DeleteRiotMessagingServiceV1Entitlements structure.
type DeleteRiotMessagingServiceV1EntitlementsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRiotMessagingServiceV1EntitlementsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteRiotMessagingServiceV1EntitlementsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRiotMessagingServiceV1EntitlementsNoContent creates a DeleteRiotMessagingServiceV1EntitlementsNoContent with default headers values
func NewDeleteRiotMessagingServiceV1EntitlementsNoContent() *DeleteRiotMessagingServiceV1EntitlementsNoContent {
	return &DeleteRiotMessagingServiceV1EntitlementsNoContent{}
}

/*DeleteRiotMessagingServiceV1EntitlementsNoContent handles this case with default header values.

No content
*/
type DeleteRiotMessagingServiceV1EntitlementsNoContent struct {
}

func (o *DeleteRiotMessagingServiceV1EntitlementsNoContent) Error() string {
	return fmt.Sprintf("[DELETE /riot-messaging-service/v1/entitlements][%d] deleteRiotMessagingServiceV1EntitlementsNoContent ", 204)
}

func (o *DeleteRiotMessagingServiceV1EntitlementsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
