// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteLolChatV1ConversationsActiveParams creates a new DeleteLolChatV1ConversationsActiveParams object
// with the default values initialized.
func NewDeleteLolChatV1ConversationsActiveParams() *DeleteLolChatV1ConversationsActiveParams {

	return &DeleteLolChatV1ConversationsActiveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLolChatV1ConversationsActiveParamsWithTimeout creates a new DeleteLolChatV1ConversationsActiveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteLolChatV1ConversationsActiveParamsWithTimeout(timeout time.Duration) *DeleteLolChatV1ConversationsActiveParams {

	return &DeleteLolChatV1ConversationsActiveParams{

		timeout: timeout,
	}
}

// NewDeleteLolChatV1ConversationsActiveParamsWithContext creates a new DeleteLolChatV1ConversationsActiveParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteLolChatV1ConversationsActiveParamsWithContext(ctx context.Context) *DeleteLolChatV1ConversationsActiveParams {

	return &DeleteLolChatV1ConversationsActiveParams{

		Context: ctx,
	}
}

// NewDeleteLolChatV1ConversationsActiveParamsWithHTTPClient creates a new DeleteLolChatV1ConversationsActiveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteLolChatV1ConversationsActiveParamsWithHTTPClient(client *http.Client) *DeleteLolChatV1ConversationsActiveParams {

	return &DeleteLolChatV1ConversationsActiveParams{
		HTTPClient: client,
	}
}

/*DeleteLolChatV1ConversationsActiveParams contains all the parameters to send to the API endpoint
for the delete lol chat v1 conversations active operation typically these are written to a http.Request
*/
type DeleteLolChatV1ConversationsActiveParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete lol chat v1 conversations active params
func (o *DeleteLolChatV1ConversationsActiveParams) WithTimeout(timeout time.Duration) *DeleteLolChatV1ConversationsActiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete lol chat v1 conversations active params
func (o *DeleteLolChatV1ConversationsActiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete lol chat v1 conversations active params
func (o *DeleteLolChatV1ConversationsActiveParams) WithContext(ctx context.Context) *DeleteLolChatV1ConversationsActiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete lol chat v1 conversations active params
func (o *DeleteLolChatV1ConversationsActiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete lol chat v1 conversations active params
func (o *DeleteLolChatV1ConversationsActiveParams) WithHTTPClient(client *http.Client) *DeleteLolChatV1ConversationsActiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete lol chat v1 conversations active params
func (o *DeleteLolChatV1ConversationsActiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLolChatV1ConversationsActiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
