// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams creates a new DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams object
// with the default values initialized.
func NewDeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams() *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams {
	var ()
	return &DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParamsWithTimeout creates a new DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParamsWithTimeout(timeout time.Duration) *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams {
	var ()
	return &DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams{

		timeout: timeout,
	}
}

// NewDeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParamsWithContext creates a new DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParamsWithContext(ctx context.Context) *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams {
	var ()
	return &DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams{

		Context: ctx,
	}
}

// NewDeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParamsWithHTTPClient creates a new DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParamsWithHTTPClient(client *http.Client) *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams {
	var ()
	return &DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams{
		HTTPClient: client,
	}
}

/*DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams contains all the parameters to send to the API endpoint
for the delete lol suggested players v1 suggested players by summoner Id operation typically these are written to a http.Request
*/
type DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams struct {

	/*SummonerID*/
	SummonerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete lol suggested players v1 suggested players by summoner Id params
func (o *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams) WithTimeout(timeout time.Duration) *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete lol suggested players v1 suggested players by summoner Id params
func (o *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete lol suggested players v1 suggested players by summoner Id params
func (o *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams) WithContext(ctx context.Context) *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete lol suggested players v1 suggested players by summoner Id params
func (o *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete lol suggested players v1 suggested players by summoner Id params
func (o *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams) WithHTTPClient(client *http.Client) *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete lol suggested players v1 suggested players by summoner Id params
func (o *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSummonerID adds the summonerID to the delete lol suggested players v1 suggested players by summoner Id params
func (o *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams) WithSummonerID(summonerID int64) *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams {
	o.SetSummonerID(summonerID)
	return o
}

// SetSummonerID adds the summonerId to the delete lol suggested players v1 suggested players by summoner Id params
func (o *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams) SetSummonerID(summonerID int64) {
	o.SummonerID = summonerID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLolSuggestedPlayersV1SuggestedPlayersBySummonerIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param summonerId
	if err := r.SetPathParam("summonerId", swag.FormatInt64(o.SummonerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
