// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLolPerksV1PagesByIDReader is a Reader for the DeleteLolPerksV1PagesByID structure.
type DeleteLolPerksV1PagesByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLolPerksV1PagesByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLolPerksV1PagesByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteLolPerksV1PagesByIDOK creates a DeleteLolPerksV1PagesByIDOK with default headers values
func NewDeleteLolPerksV1PagesByIDOK() *DeleteLolPerksV1PagesByIDOK {
	return &DeleteLolPerksV1PagesByIDOK{}
}

/*DeleteLolPerksV1PagesByIDOK handles this case with default header values.

Successful response
*/
type DeleteLolPerksV1PagesByIDOK struct {
	Payload interface{}
}

func (o *DeleteLolPerksV1PagesByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /lol-perks/v1/pages/{id}][%d] deleteLolPerksV1PagesByIdOK  %+v", 200, o.Payload)
}

func (o *DeleteLolPerksV1PagesByIDOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteLolPerksV1PagesByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
