// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLolChatV1BlockedPlayersByIDReader is a Reader for the DeleteLolChatV1BlockedPlayersByID structure.
type DeleteLolChatV1BlockedPlayersByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLolChatV1BlockedPlayersByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLolChatV1BlockedPlayersByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteLolChatV1BlockedPlayersByIDOK creates a DeleteLolChatV1BlockedPlayersByIDOK with default headers values
func NewDeleteLolChatV1BlockedPlayersByIDOK() *DeleteLolChatV1BlockedPlayersByIDOK {
	return &DeleteLolChatV1BlockedPlayersByIDOK{}
}

/*DeleteLolChatV1BlockedPlayersByIDOK handles this case with default header values.

Successful response
*/
type DeleteLolChatV1BlockedPlayersByIDOK struct {
	Payload interface{}
}

func (o *DeleteLolChatV1BlockedPlayersByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /lol-chat/v1/blocked-players/{id}][%d] deleteLolChatV1BlockedPlayersByIdOK  %+v", 200, o.Payload)
}

func (o *DeleteLolChatV1BlockedPlayersByIDOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteLolChatV1BlockedPlayersByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
