// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteLolChatV1ErrorsByIDParams creates a new DeleteLolChatV1ErrorsByIDParams object
// with the default values initialized.
func NewDeleteLolChatV1ErrorsByIDParams() *DeleteLolChatV1ErrorsByIDParams {
	var ()
	return &DeleteLolChatV1ErrorsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLolChatV1ErrorsByIDParamsWithTimeout creates a new DeleteLolChatV1ErrorsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteLolChatV1ErrorsByIDParamsWithTimeout(timeout time.Duration) *DeleteLolChatV1ErrorsByIDParams {
	var ()
	return &DeleteLolChatV1ErrorsByIDParams{

		timeout: timeout,
	}
}

// NewDeleteLolChatV1ErrorsByIDParamsWithContext creates a new DeleteLolChatV1ErrorsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteLolChatV1ErrorsByIDParamsWithContext(ctx context.Context) *DeleteLolChatV1ErrorsByIDParams {
	var ()
	return &DeleteLolChatV1ErrorsByIDParams{

		Context: ctx,
	}
}

// NewDeleteLolChatV1ErrorsByIDParamsWithHTTPClient creates a new DeleteLolChatV1ErrorsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteLolChatV1ErrorsByIDParamsWithHTTPClient(client *http.Client) *DeleteLolChatV1ErrorsByIDParams {
	var ()
	return &DeleteLolChatV1ErrorsByIDParams{
		HTTPClient: client,
	}
}

/*DeleteLolChatV1ErrorsByIDParams contains all the parameters to send to the API endpoint
for the delete lol chat v1 errors by Id operation typically these are written to a http.Request
*/
type DeleteLolChatV1ErrorsByIDParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete lol chat v1 errors by Id params
func (o *DeleteLolChatV1ErrorsByIDParams) WithTimeout(timeout time.Duration) *DeleteLolChatV1ErrorsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete lol chat v1 errors by Id params
func (o *DeleteLolChatV1ErrorsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete lol chat v1 errors by Id params
func (o *DeleteLolChatV1ErrorsByIDParams) WithContext(ctx context.Context) *DeleteLolChatV1ErrorsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete lol chat v1 errors by Id params
func (o *DeleteLolChatV1ErrorsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete lol chat v1 errors by Id params
func (o *DeleteLolChatV1ErrorsByIDParams) WithHTTPClient(client *http.Client) *DeleteLolChatV1ErrorsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete lol chat v1 errors by Id params
func (o *DeleteLolChatV1ErrorsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete lol chat v1 errors by Id params
func (o *DeleteLolChatV1ErrorsByIDParams) WithID(id int64) *DeleteLolChatV1ErrorsByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete lol chat v1 errors by Id params
func (o *DeleteLolChatV1ErrorsByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLolChatV1ErrorsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
