// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolClashV1BracketByBracketIDParams creates a new GetLolClashV1BracketByBracketIDParams object
// with the default values initialized.
func NewGetLolClashV1BracketByBracketIDParams() *GetLolClashV1BracketByBracketIDParams {
	var ()
	return &GetLolClashV1BracketByBracketIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolClashV1BracketByBracketIDParamsWithTimeout creates a new GetLolClashV1BracketByBracketIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolClashV1BracketByBracketIDParamsWithTimeout(timeout time.Duration) *GetLolClashV1BracketByBracketIDParams {
	var ()
	return &GetLolClashV1BracketByBracketIDParams{

		timeout: timeout,
	}
}

// NewGetLolClashV1BracketByBracketIDParamsWithContext creates a new GetLolClashV1BracketByBracketIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolClashV1BracketByBracketIDParamsWithContext(ctx context.Context) *GetLolClashV1BracketByBracketIDParams {
	var ()
	return &GetLolClashV1BracketByBracketIDParams{

		Context: ctx,
	}
}

// NewGetLolClashV1BracketByBracketIDParamsWithHTTPClient creates a new GetLolClashV1BracketByBracketIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolClashV1BracketByBracketIDParamsWithHTTPClient(client *http.Client) *GetLolClashV1BracketByBracketIDParams {
	var ()
	return &GetLolClashV1BracketByBracketIDParams{
		HTTPClient: client,
	}
}

/*GetLolClashV1BracketByBracketIDParams contains all the parameters to send to the API endpoint
for the get lol clash v1 bracket by bracket Id operation typically these are written to a http.Request
*/
type GetLolClashV1BracketByBracketIDParams struct {

	/*BracketID*/
	BracketID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol clash v1 bracket by bracket Id params
func (o *GetLolClashV1BracketByBracketIDParams) WithTimeout(timeout time.Duration) *GetLolClashV1BracketByBracketIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol clash v1 bracket by bracket Id params
func (o *GetLolClashV1BracketByBracketIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol clash v1 bracket by bracket Id params
func (o *GetLolClashV1BracketByBracketIDParams) WithContext(ctx context.Context) *GetLolClashV1BracketByBracketIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol clash v1 bracket by bracket Id params
func (o *GetLolClashV1BracketByBracketIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol clash v1 bracket by bracket Id params
func (o *GetLolClashV1BracketByBracketIDParams) WithHTTPClient(client *http.Client) *GetLolClashV1BracketByBracketIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol clash v1 bracket by bracket Id params
func (o *GetLolClashV1BracketByBracketIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBracketID adds the bracketID to the get lol clash v1 bracket by bracket Id params
func (o *GetLolClashV1BracketByBracketIDParams) WithBracketID(bracketID int64) *GetLolClashV1BracketByBracketIDParams {
	o.SetBracketID(bracketID)
	return o
}

// SetBracketID adds the bracketId to the get lol clash v1 bracket by bracket Id params
func (o *GetLolClashV1BracketByBracketIDParams) SetBracketID(bracketID int64) {
	o.BracketID = bracketID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolClashV1BracketByBracketIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bracketId
	if err := r.SetPathParam("bracketId", swag.FormatInt64(o.BracketID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
