// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolPersonalizedOffersV1StatusParams creates a new GetLolPersonalizedOffersV1StatusParams object
// with the default values initialized.
func NewGetLolPersonalizedOffersV1StatusParams() *GetLolPersonalizedOffersV1StatusParams {

	return &GetLolPersonalizedOffersV1StatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolPersonalizedOffersV1StatusParamsWithTimeout creates a new GetLolPersonalizedOffersV1StatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolPersonalizedOffersV1StatusParamsWithTimeout(timeout time.Duration) *GetLolPersonalizedOffersV1StatusParams {

	return &GetLolPersonalizedOffersV1StatusParams{

		timeout: timeout,
	}
}

// NewGetLolPersonalizedOffersV1StatusParamsWithContext creates a new GetLolPersonalizedOffersV1StatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolPersonalizedOffersV1StatusParamsWithContext(ctx context.Context) *GetLolPersonalizedOffersV1StatusParams {

	return &GetLolPersonalizedOffersV1StatusParams{

		Context: ctx,
	}
}

// NewGetLolPersonalizedOffersV1StatusParamsWithHTTPClient creates a new GetLolPersonalizedOffersV1StatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolPersonalizedOffersV1StatusParamsWithHTTPClient(client *http.Client) *GetLolPersonalizedOffersV1StatusParams {

	return &GetLolPersonalizedOffersV1StatusParams{
		HTTPClient: client,
	}
}

/*GetLolPersonalizedOffersV1StatusParams contains all the parameters to send to the API endpoint
for the get lol personalized offers v1 status operation typically these are written to a http.Request
*/
type GetLolPersonalizedOffersV1StatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol personalized offers v1 status params
func (o *GetLolPersonalizedOffersV1StatusParams) WithTimeout(timeout time.Duration) *GetLolPersonalizedOffersV1StatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol personalized offers v1 status params
func (o *GetLolPersonalizedOffersV1StatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol personalized offers v1 status params
func (o *GetLolPersonalizedOffersV1StatusParams) WithContext(ctx context.Context) *GetLolPersonalizedOffersV1StatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol personalized offers v1 status params
func (o *GetLolPersonalizedOffersV1StatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol personalized offers v1 status params
func (o *GetLolPersonalizedOffersV1StatusParams) WithHTTPClient(client *http.Client) *GetLolPersonalizedOffersV1StatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol personalized offers v1 status params
func (o *GetLolPersonalizedOffersV1StatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolPersonalizedOffersV1StatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
