// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryReader is a Reader for the GetLolCollectionsV1InventoriesBySummonerIDChampionMastery structure.
type GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK creates a GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK with default headers values
func NewGetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK() *GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK {
	return &GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK{}
}

/*GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK handles this case with default header values.

Successful response
*/
type GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK struct {
	Payload []*models.LolCollectionsCollectionsChampionMastery
}

func (o *GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK) Error() string {
	return fmt.Sprintf("[GET /lol-collections/v1/inventories/{summonerId}/champion-mastery][%d] getLolCollectionsV1InventoriesBySummonerIdChampionMasteryOK  %+v", 200, o.Payload)
}

func (o *GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK) GetPayload() []*models.LolCollectionsCollectionsChampionMastery {
	return o.Payload
}

func (o *GetLolCollectionsV1InventoriesBySummonerIDChampionMasteryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
