// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVoiceChatV2DevicesCapturePermissionParams creates a new GetVoiceChatV2DevicesCapturePermissionParams object
// with the default values initialized.
func NewGetVoiceChatV2DevicesCapturePermissionParams() *GetVoiceChatV2DevicesCapturePermissionParams {

	return &GetVoiceChatV2DevicesCapturePermissionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVoiceChatV2DevicesCapturePermissionParamsWithTimeout creates a new GetVoiceChatV2DevicesCapturePermissionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVoiceChatV2DevicesCapturePermissionParamsWithTimeout(timeout time.Duration) *GetVoiceChatV2DevicesCapturePermissionParams {

	return &GetVoiceChatV2DevicesCapturePermissionParams{

		timeout: timeout,
	}
}

// NewGetVoiceChatV2DevicesCapturePermissionParamsWithContext creates a new GetVoiceChatV2DevicesCapturePermissionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVoiceChatV2DevicesCapturePermissionParamsWithContext(ctx context.Context) *GetVoiceChatV2DevicesCapturePermissionParams {

	return &GetVoiceChatV2DevicesCapturePermissionParams{

		Context: ctx,
	}
}

// NewGetVoiceChatV2DevicesCapturePermissionParamsWithHTTPClient creates a new GetVoiceChatV2DevicesCapturePermissionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVoiceChatV2DevicesCapturePermissionParamsWithHTTPClient(client *http.Client) *GetVoiceChatV2DevicesCapturePermissionParams {

	return &GetVoiceChatV2DevicesCapturePermissionParams{
		HTTPClient: client,
	}
}

/*GetVoiceChatV2DevicesCapturePermissionParams contains all the parameters to send to the API endpoint
for the get voice chat v2 devices capture permission operation typically these are written to a http.Request
*/
type GetVoiceChatV2DevicesCapturePermissionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get voice chat v2 devices capture permission params
func (o *GetVoiceChatV2DevicesCapturePermissionParams) WithTimeout(timeout time.Duration) *GetVoiceChatV2DevicesCapturePermissionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get voice chat v2 devices capture permission params
func (o *GetVoiceChatV2DevicesCapturePermissionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get voice chat v2 devices capture permission params
func (o *GetVoiceChatV2DevicesCapturePermissionParams) WithContext(ctx context.Context) *GetVoiceChatV2DevicesCapturePermissionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get voice chat v2 devices capture permission params
func (o *GetVoiceChatV2DevicesCapturePermissionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get voice chat v2 devices capture permission params
func (o *GetVoiceChatV2DevicesCapturePermissionParams) WithHTTPClient(client *http.Client) *GetVoiceChatV2DevicesCapturePermissionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get voice chat v2 devices capture permission params
func (o *GetVoiceChatV2DevicesCapturePermissionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetVoiceChatV2DevicesCapturePermissionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
