// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolSummonerV1CurrentSummonerReader is a Reader for the GetLolSummonerV1CurrentSummoner structure.
type GetLolSummonerV1CurrentSummonerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolSummonerV1CurrentSummonerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolSummonerV1CurrentSummonerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolSummonerV1CurrentSummonerOK creates a GetLolSummonerV1CurrentSummonerOK with default headers values
func NewGetLolSummonerV1CurrentSummonerOK() *GetLolSummonerV1CurrentSummonerOK {
	return &GetLolSummonerV1CurrentSummonerOK{}
}

/*GetLolSummonerV1CurrentSummonerOK handles this case with default header values.

Successful response
*/
type GetLolSummonerV1CurrentSummonerOK struct {
	Payload *models.LolSummonerSummoner
}

func (o *GetLolSummonerV1CurrentSummonerOK) Error() string {
	return fmt.Sprintf("[GET /lol-summoner/v1/current-summoner][%d] getLolSummonerV1CurrentSummonerOK  %+v", 200, o.Payload)
}

func (o *GetLolSummonerV1CurrentSummonerOK) GetPayload() *models.LolSummonerSummoner {
	return o.Payload
}

func (o *GetLolSummonerV1CurrentSummonerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolSummonerSummoner)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
