// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetLolGameflowV1EarlyExitNotificationsMissionsReader is a Reader for the GetLolGameflowV1EarlyExitNotificationsMissions structure.
type GetLolGameflowV1EarlyExitNotificationsMissionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolGameflowV1EarlyExitNotificationsMissionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolGameflowV1EarlyExitNotificationsMissionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolGameflowV1EarlyExitNotificationsMissionsOK creates a GetLolGameflowV1EarlyExitNotificationsMissionsOK with default headers values
func NewGetLolGameflowV1EarlyExitNotificationsMissionsOK() *GetLolGameflowV1EarlyExitNotificationsMissionsOK {
	return &GetLolGameflowV1EarlyExitNotificationsMissionsOK{}
}

/*GetLolGameflowV1EarlyExitNotificationsMissionsOK handles this case with default header values.

Successful response
*/
type GetLolGameflowV1EarlyExitNotificationsMissionsOK struct {
	Payload []interface{}
}

func (o *GetLolGameflowV1EarlyExitNotificationsMissionsOK) Error() string {
	return fmt.Sprintf("[GET /lol-gameflow/v1/early-exit-notifications/missions][%d] getLolGameflowV1EarlyExitNotificationsMissionsOK  %+v", 200, o.Payload)
}

func (o *GetLolGameflowV1EarlyExitNotificationsMissionsOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *GetLolGameflowV1EarlyExitNotificationsMissionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
