// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolChampSelectV1GridChampionsByChampionIDParams creates a new GetLolChampSelectV1GridChampionsByChampionIDParams object
// with the default values initialized.
func NewGetLolChampSelectV1GridChampionsByChampionIDParams() *GetLolChampSelectV1GridChampionsByChampionIDParams {
	var ()
	return &GetLolChampSelectV1GridChampionsByChampionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolChampSelectV1GridChampionsByChampionIDParamsWithTimeout creates a new GetLolChampSelectV1GridChampionsByChampionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolChampSelectV1GridChampionsByChampionIDParamsWithTimeout(timeout time.Duration) *GetLolChampSelectV1GridChampionsByChampionIDParams {
	var ()
	return &GetLolChampSelectV1GridChampionsByChampionIDParams{

		timeout: timeout,
	}
}

// NewGetLolChampSelectV1GridChampionsByChampionIDParamsWithContext creates a new GetLolChampSelectV1GridChampionsByChampionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolChampSelectV1GridChampionsByChampionIDParamsWithContext(ctx context.Context) *GetLolChampSelectV1GridChampionsByChampionIDParams {
	var ()
	return &GetLolChampSelectV1GridChampionsByChampionIDParams{

		Context: ctx,
	}
}

// NewGetLolChampSelectV1GridChampionsByChampionIDParamsWithHTTPClient creates a new GetLolChampSelectV1GridChampionsByChampionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolChampSelectV1GridChampionsByChampionIDParamsWithHTTPClient(client *http.Client) *GetLolChampSelectV1GridChampionsByChampionIDParams {
	var ()
	return &GetLolChampSelectV1GridChampionsByChampionIDParams{
		HTTPClient: client,
	}
}

/*GetLolChampSelectV1GridChampionsByChampionIDParams contains all the parameters to send to the API endpoint
for the get lol champ select v1 grid champions by champion Id operation typically these are written to a http.Request
*/
type GetLolChampSelectV1GridChampionsByChampionIDParams struct {

	/*ChampionID*/
	ChampionID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol champ select v1 grid champions by champion Id params
func (o *GetLolChampSelectV1GridChampionsByChampionIDParams) WithTimeout(timeout time.Duration) *GetLolChampSelectV1GridChampionsByChampionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol champ select v1 grid champions by champion Id params
func (o *GetLolChampSelectV1GridChampionsByChampionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol champ select v1 grid champions by champion Id params
func (o *GetLolChampSelectV1GridChampionsByChampionIDParams) WithContext(ctx context.Context) *GetLolChampSelectV1GridChampionsByChampionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol champ select v1 grid champions by champion Id params
func (o *GetLolChampSelectV1GridChampionsByChampionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol champ select v1 grid champions by champion Id params
func (o *GetLolChampSelectV1GridChampionsByChampionIDParams) WithHTTPClient(client *http.Client) *GetLolChampSelectV1GridChampionsByChampionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol champ select v1 grid champions by champion Id params
func (o *GetLolChampSelectV1GridChampionsByChampionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChampionID adds the championID to the get lol champ select v1 grid champions by champion Id params
func (o *GetLolChampSelectV1GridChampionsByChampionIDParams) WithChampionID(championID int32) *GetLolChampSelectV1GridChampionsByChampionIDParams {
	o.SetChampionID(championID)
	return o
}

// SetChampionID adds the championId to the get lol champ select v1 grid champions by champion Id params
func (o *GetLolChampSelectV1GridChampionsByChampionIDParams) SetChampionID(championID int32) {
	o.ChampionID = championID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolChampSelectV1GridChampionsByChampionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param championId
	if err := r.SetPathParam("championId", swag.FormatInt32(o.ChampionID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
