// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolChatV1FriendRequestsReader is a Reader for the GetLolChatV1FriendRequests structure.
type GetLolChatV1FriendRequestsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolChatV1FriendRequestsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolChatV1FriendRequestsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolChatV1FriendRequestsOK creates a GetLolChatV1FriendRequestsOK with default headers values
func NewGetLolChatV1FriendRequestsOK() *GetLolChatV1FriendRequestsOK {
	return &GetLolChatV1FriendRequestsOK{}
}

/*GetLolChatV1FriendRequestsOK handles this case with default header values.

Successful response
*/
type GetLolChatV1FriendRequestsOK struct {
	Payload []*models.LolChatFriendRequestResource
}

func (o *GetLolChatV1FriendRequestsOK) Error() string {
	return fmt.Sprintf("[GET /lol-chat/v1/friend-requests][%d] getLolChatV1FriendRequestsOK  %+v", 200, o.Payload)
}

func (o *GetLolChatV1FriendRequestsOK) GetPayload() []*models.LolChatFriendRequestResource {
	return o.Payload
}

func (o *GetLolChatV1FriendRequestsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
