// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVoiceChatV1ErrorsParams creates a new GetVoiceChatV1ErrorsParams object
// with the default values initialized.
func NewGetVoiceChatV1ErrorsParams() *GetVoiceChatV1ErrorsParams {

	return &GetVoiceChatV1ErrorsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVoiceChatV1ErrorsParamsWithTimeout creates a new GetVoiceChatV1ErrorsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVoiceChatV1ErrorsParamsWithTimeout(timeout time.Duration) *GetVoiceChatV1ErrorsParams {

	return &GetVoiceChatV1ErrorsParams{

		timeout: timeout,
	}
}

// NewGetVoiceChatV1ErrorsParamsWithContext creates a new GetVoiceChatV1ErrorsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVoiceChatV1ErrorsParamsWithContext(ctx context.Context) *GetVoiceChatV1ErrorsParams {

	return &GetVoiceChatV1ErrorsParams{

		Context: ctx,
	}
}

// NewGetVoiceChatV1ErrorsParamsWithHTTPClient creates a new GetVoiceChatV1ErrorsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVoiceChatV1ErrorsParamsWithHTTPClient(client *http.Client) *GetVoiceChatV1ErrorsParams {

	return &GetVoiceChatV1ErrorsParams{
		HTTPClient: client,
	}
}

/*GetVoiceChatV1ErrorsParams contains all the parameters to send to the API endpoint
for the get voice chat v1 errors operation typically these are written to a http.Request
*/
type GetVoiceChatV1ErrorsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get voice chat v1 errors params
func (o *GetVoiceChatV1ErrorsParams) WithTimeout(timeout time.Duration) *GetVoiceChatV1ErrorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get voice chat v1 errors params
func (o *GetVoiceChatV1ErrorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get voice chat v1 errors params
func (o *GetVoiceChatV1ErrorsParams) WithContext(ctx context.Context) *GetVoiceChatV1ErrorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get voice chat v1 errors params
func (o *GetVoiceChatV1ErrorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get voice chat v1 errors params
func (o *GetVoiceChatV1ErrorsParams) WithHTTPClient(client *http.Client) *GetVoiceChatV1ErrorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get voice chat v1 errors params
func (o *GetVoiceChatV1ErrorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetVoiceChatV1ErrorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
