// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolClashV2PlaymodeRestrictedParams creates a new GetLolClashV2PlaymodeRestrictedParams object
// with the default values initialized.
func NewGetLolClashV2PlaymodeRestrictedParams() *GetLolClashV2PlaymodeRestrictedParams {

	return &GetLolClashV2PlaymodeRestrictedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolClashV2PlaymodeRestrictedParamsWithTimeout creates a new GetLolClashV2PlaymodeRestrictedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolClashV2PlaymodeRestrictedParamsWithTimeout(timeout time.Duration) *GetLolClashV2PlaymodeRestrictedParams {

	return &GetLolClashV2PlaymodeRestrictedParams{

		timeout: timeout,
	}
}

// NewGetLolClashV2PlaymodeRestrictedParamsWithContext creates a new GetLolClashV2PlaymodeRestrictedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolClashV2PlaymodeRestrictedParamsWithContext(ctx context.Context) *GetLolClashV2PlaymodeRestrictedParams {

	return &GetLolClashV2PlaymodeRestrictedParams{

		Context: ctx,
	}
}

// NewGetLolClashV2PlaymodeRestrictedParamsWithHTTPClient creates a new GetLolClashV2PlaymodeRestrictedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolClashV2PlaymodeRestrictedParamsWithHTTPClient(client *http.Client) *GetLolClashV2PlaymodeRestrictedParams {

	return &GetLolClashV2PlaymodeRestrictedParams{
		HTTPClient: client,
	}
}

/*GetLolClashV2PlaymodeRestrictedParams contains all the parameters to send to the API endpoint
for the get lol clash v2 playmode restricted operation typically these are written to a http.Request
*/
type GetLolClashV2PlaymodeRestrictedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol clash v2 playmode restricted params
func (o *GetLolClashV2PlaymodeRestrictedParams) WithTimeout(timeout time.Duration) *GetLolClashV2PlaymodeRestrictedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol clash v2 playmode restricted params
func (o *GetLolClashV2PlaymodeRestrictedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol clash v2 playmode restricted params
func (o *GetLolClashV2PlaymodeRestrictedParams) WithContext(ctx context.Context) *GetLolClashV2PlaymodeRestrictedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol clash v2 playmode restricted params
func (o *GetLolClashV2PlaymodeRestrictedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol clash v2 playmode restricted params
func (o *GetLolClashV2PlaymodeRestrictedParams) WithHTTPClient(client *http.Client) *GetLolClashV2PlaymodeRestrictedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol clash v2 playmode restricted params
func (o *GetLolClashV2PlaymodeRestrictedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolClashV2PlaymodeRestrictedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
