// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClientConfigV2NamespaceByNamespacePlayerParams creates a new GetClientConfigV2NamespaceByNamespacePlayerParams object
// with the default values initialized.
func NewGetClientConfigV2NamespaceByNamespacePlayerParams() *GetClientConfigV2NamespaceByNamespacePlayerParams {
	var ()
	return &GetClientConfigV2NamespaceByNamespacePlayerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetClientConfigV2NamespaceByNamespacePlayerParamsWithTimeout creates a new GetClientConfigV2NamespaceByNamespacePlayerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetClientConfigV2NamespaceByNamespacePlayerParamsWithTimeout(timeout time.Duration) *GetClientConfigV2NamespaceByNamespacePlayerParams {
	var ()
	return &GetClientConfigV2NamespaceByNamespacePlayerParams{

		timeout: timeout,
	}
}

// NewGetClientConfigV2NamespaceByNamespacePlayerParamsWithContext creates a new GetClientConfigV2NamespaceByNamespacePlayerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetClientConfigV2NamespaceByNamespacePlayerParamsWithContext(ctx context.Context) *GetClientConfigV2NamespaceByNamespacePlayerParams {
	var ()
	return &GetClientConfigV2NamespaceByNamespacePlayerParams{

		Context: ctx,
	}
}

// NewGetClientConfigV2NamespaceByNamespacePlayerParamsWithHTTPClient creates a new GetClientConfigV2NamespaceByNamespacePlayerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetClientConfigV2NamespaceByNamespacePlayerParamsWithHTTPClient(client *http.Client) *GetClientConfigV2NamespaceByNamespacePlayerParams {
	var ()
	return &GetClientConfigV2NamespaceByNamespacePlayerParams{
		HTTPClient: client,
	}
}

/*GetClientConfigV2NamespaceByNamespacePlayerParams contains all the parameters to send to the API endpoint
for the get client config v2 namespace by namespace player operation typically these are written to a http.Request
*/
type GetClientConfigV2NamespaceByNamespacePlayerParams struct {

	/*Namespace*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get client config v2 namespace by namespace player params
func (o *GetClientConfigV2NamespaceByNamespacePlayerParams) WithTimeout(timeout time.Duration) *GetClientConfigV2NamespaceByNamespacePlayerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get client config v2 namespace by namespace player params
func (o *GetClientConfigV2NamespaceByNamespacePlayerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get client config v2 namespace by namespace player params
func (o *GetClientConfigV2NamespaceByNamespacePlayerParams) WithContext(ctx context.Context) *GetClientConfigV2NamespaceByNamespacePlayerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get client config v2 namespace by namespace player params
func (o *GetClientConfigV2NamespaceByNamespacePlayerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get client config v2 namespace by namespace player params
func (o *GetClientConfigV2NamespaceByNamespacePlayerParams) WithHTTPClient(client *http.Client) *GetClientConfigV2NamespaceByNamespacePlayerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get client config v2 namespace by namespace player params
func (o *GetClientConfigV2NamespaceByNamespacePlayerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the get client config v2 namespace by namespace player params
func (o *GetClientConfigV2NamespaceByNamespacePlayerParams) WithNamespace(namespace string) *GetClientConfigV2NamespaceByNamespacePlayerParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get client config v2 namespace by namespace player params
func (o *GetClientConfigV2NamespaceByNamespacePlayerParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *GetClientConfigV2NamespaceByNamespacePlayerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
