// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolMapsV1MapByIDReader is a Reader for the GetLolMapsV1MapByID structure.
type GetLolMapsV1MapByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolMapsV1MapByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolMapsV1MapByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolMapsV1MapByIDOK creates a GetLolMapsV1MapByIDOK with default headers values
func NewGetLolMapsV1MapByIDOK() *GetLolMapsV1MapByIDOK {
	return &GetLolMapsV1MapByIDOK{}
}

/*GetLolMapsV1MapByIDOK handles this case with default header values.

Successful response
*/
type GetLolMapsV1MapByIDOK struct {
	Payload *models.LolMapsMaps
}

func (o *GetLolMapsV1MapByIDOK) Error() string {
	return fmt.Sprintf("[GET /lol-maps/v1/map/{id}][%d] getLolMapsV1MapByIdOK  %+v", 200, o.Payload)
}

func (o *GetLolMapsV1MapByIDOK) GetPayload() *models.LolMapsMaps {
	return o.Payload
}

func (o *GetLolMapsV1MapByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolMapsMaps)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
