// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolLoadoutsV4LoadoutsScopeAccountReader is a Reader for the GetLolLoadoutsV4LoadoutsScopeAccount structure.
type GetLolLoadoutsV4LoadoutsScopeAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolLoadoutsV4LoadoutsScopeAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolLoadoutsV4LoadoutsScopeAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolLoadoutsV4LoadoutsScopeAccountOK creates a GetLolLoadoutsV4LoadoutsScopeAccountOK with default headers values
func NewGetLolLoadoutsV4LoadoutsScopeAccountOK() *GetLolLoadoutsV4LoadoutsScopeAccountOK {
	return &GetLolLoadoutsV4LoadoutsScopeAccountOK{}
}

/*GetLolLoadoutsV4LoadoutsScopeAccountOK handles this case with default header values.

Successful response
*/
type GetLolLoadoutsV4LoadoutsScopeAccountOK struct {
	Payload []*models.LolLoadoutsScopedLoadout
}

func (o *GetLolLoadoutsV4LoadoutsScopeAccountOK) Error() string {
	return fmt.Sprintf("[GET /lol-loadouts/v4/loadouts/scope/account][%d] getLolLoadoutsV4LoadoutsScopeAccountOK  %+v", 200, o.Payload)
}

func (o *GetLolLoadoutsV4LoadoutsScopeAccountOK) GetPayload() []*models.LolLoadoutsScopedLoadout {
	return o.Payload
}

func (o *GetLolLoadoutsV4LoadoutsScopeAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
