// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetVoiceChatV2StateReader is a Reader for the GetVoiceChatV2State structure.
type GetVoiceChatV2StateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVoiceChatV2StateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVoiceChatV2StateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetVoiceChatV2StateOK creates a GetVoiceChatV2StateOK with default headers values
func NewGetVoiceChatV2StateOK() *GetVoiceChatV2StateOK {
	return &GetVoiceChatV2StateOK{}
}

/*GetVoiceChatV2StateOK handles this case with default header values.

Successful response
*/
type GetVoiceChatV2StateOK struct {
	Payload *models.VoiceChatStateResource
}

func (o *GetVoiceChatV2StateOK) Error() string {
	return fmt.Sprintf("[GET /voice-chat/v2/state][%d] getVoiceChatV2StateOK  %+v", 200, o.Payload)
}

func (o *GetVoiceChatV2StateOK) GetPayload() *models.VoiceChatStateResource {
	return o.Payload
}

func (o *GetVoiceChatV2StateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VoiceChatStateResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
