// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolChatV1ConfigReader is a Reader for the GetLolChatV1Config structure.
type GetLolChatV1ConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolChatV1ConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolChatV1ConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolChatV1ConfigOK creates a GetLolChatV1ConfigOK with default headers values
func NewGetLolChatV1ConfigOK() *GetLolChatV1ConfigOK {
	return &GetLolChatV1ConfigOK{}
}

/*GetLolChatV1ConfigOK handles this case with default header values.

Successful response
*/
type GetLolChatV1ConfigOK struct {
	Payload *models.LolChatChatServiceDynamicClientConfig
}

func (o *GetLolChatV1ConfigOK) Error() string {
	return fmt.Sprintf("[GET /lol-chat/v1/config][%d] getLolChatV1ConfigOK  %+v", 200, o.Payload)
}

func (o *GetLolChatV1ConfigOK) GetPayload() *models.LolChatChatServiceDynamicClientConfig {
	return o.Payload
}

func (o *GetLolChatV1ConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolChatChatServiceDynamicClientConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
