// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolMapsV1MapsParams creates a new GetLolMapsV1MapsParams object
// with the default values initialized.
func NewGetLolMapsV1MapsParams() *GetLolMapsV1MapsParams {

	return &GetLolMapsV1MapsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolMapsV1MapsParamsWithTimeout creates a new GetLolMapsV1MapsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolMapsV1MapsParamsWithTimeout(timeout time.Duration) *GetLolMapsV1MapsParams {

	return &GetLolMapsV1MapsParams{

		timeout: timeout,
	}
}

// NewGetLolMapsV1MapsParamsWithContext creates a new GetLolMapsV1MapsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolMapsV1MapsParamsWithContext(ctx context.Context) *GetLolMapsV1MapsParams {

	return &GetLolMapsV1MapsParams{

		Context: ctx,
	}
}

// NewGetLolMapsV1MapsParamsWithHTTPClient creates a new GetLolMapsV1MapsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolMapsV1MapsParamsWithHTTPClient(client *http.Client) *GetLolMapsV1MapsParams {

	return &GetLolMapsV1MapsParams{
		HTTPClient: client,
	}
}

/*GetLolMapsV1MapsParams contains all the parameters to send to the API endpoint
for the get lol maps v1 maps operation typically these are written to a http.Request
*/
type GetLolMapsV1MapsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol maps v1 maps params
func (o *GetLolMapsV1MapsParams) WithTimeout(timeout time.Duration) *GetLolMapsV1MapsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol maps v1 maps params
func (o *GetLolMapsV1MapsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol maps v1 maps params
func (o *GetLolMapsV1MapsParams) WithContext(ctx context.Context) *GetLolMapsV1MapsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol maps v1 maps params
func (o *GetLolMapsV1MapsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol maps v1 maps params
func (o *GetLolMapsV1MapsParams) WithHTTPClient(client *http.Client) *GetLolMapsV1MapsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol maps v1 maps params
func (o *GetLolMapsV1MapsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolMapsV1MapsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
