// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRecofrienderV1DebugParams creates a new GetRecofrienderV1DebugParams object
// with the default values initialized.
func NewGetRecofrienderV1DebugParams() *GetRecofrienderV1DebugParams {

	return &GetRecofrienderV1DebugParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRecofrienderV1DebugParamsWithTimeout creates a new GetRecofrienderV1DebugParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRecofrienderV1DebugParamsWithTimeout(timeout time.Duration) *GetRecofrienderV1DebugParams {

	return &GetRecofrienderV1DebugParams{

		timeout: timeout,
	}
}

// NewGetRecofrienderV1DebugParamsWithContext creates a new GetRecofrienderV1DebugParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRecofrienderV1DebugParamsWithContext(ctx context.Context) *GetRecofrienderV1DebugParams {

	return &GetRecofrienderV1DebugParams{

		Context: ctx,
	}
}

// NewGetRecofrienderV1DebugParamsWithHTTPClient creates a new GetRecofrienderV1DebugParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRecofrienderV1DebugParamsWithHTTPClient(client *http.Client) *GetRecofrienderV1DebugParams {

	return &GetRecofrienderV1DebugParams{
		HTTPClient: client,
	}
}

/*GetRecofrienderV1DebugParams contains all the parameters to send to the API endpoint
for the get recofriender v1 debug operation typically these are written to a http.Request
*/
type GetRecofrienderV1DebugParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get recofriender v1 debug params
func (o *GetRecofrienderV1DebugParams) WithTimeout(timeout time.Duration) *GetRecofrienderV1DebugParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get recofriender v1 debug params
func (o *GetRecofrienderV1DebugParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get recofriender v1 debug params
func (o *GetRecofrienderV1DebugParams) WithContext(ctx context.Context) *GetRecofrienderV1DebugParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get recofriender v1 debug params
func (o *GetRecofrienderV1DebugParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get recofriender v1 debug params
func (o *GetRecofrienderV1DebugParams) WithHTTPClient(client *http.Client) *GetRecofrienderV1DebugParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get recofriender v1 debug params
func (o *GetRecofrienderV1DebugParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRecofrienderV1DebugParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
