// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolServiceStatusV1LcuStatusReader is a Reader for the GetLolServiceStatusV1LcuStatus structure.
type GetLolServiceStatusV1LcuStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolServiceStatusV1LcuStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolServiceStatusV1LcuStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolServiceStatusV1LcuStatusOK creates a GetLolServiceStatusV1LcuStatusOK with default headers values
func NewGetLolServiceStatusV1LcuStatusOK() *GetLolServiceStatusV1LcuStatusOK {
	return &GetLolServiceStatusV1LcuStatusOK{}
}

/*GetLolServiceStatusV1LcuStatusOK handles this case with default header values.

Successful response
*/
type GetLolServiceStatusV1LcuStatusOK struct {
	Payload *models.LolServiceStatusServiceStatusResource
}

func (o *GetLolServiceStatusV1LcuStatusOK) Error() string {
	return fmt.Sprintf("[GET /lol-service-status/v1/lcu-status][%d] getLolServiceStatusV1LcuStatusOK  %+v", 200, o.Payload)
}

func (o *GetLolServiceStatusV1LcuStatusOK) GetPayload() *models.LolServiceStatusServiceStatusResource {
	return o.Payload
}

func (o *GetLolServiceStatusV1LcuStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolServiceStatusServiceStatusResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
