// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetLolLoadoutsV1LoadoutsReadyReader is a Reader for the GetLolLoadoutsV1LoadoutsReady structure.
type GetLolLoadoutsV1LoadoutsReadyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolLoadoutsV1LoadoutsReadyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolLoadoutsV1LoadoutsReadyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolLoadoutsV1LoadoutsReadyOK creates a GetLolLoadoutsV1LoadoutsReadyOK with default headers values
func NewGetLolLoadoutsV1LoadoutsReadyOK() *GetLolLoadoutsV1LoadoutsReadyOK {
	return &GetLolLoadoutsV1LoadoutsReadyOK{}
}

/*GetLolLoadoutsV1LoadoutsReadyOK handles this case with default header values.

Successful response
*/
type GetLolLoadoutsV1LoadoutsReadyOK struct {
	Payload bool
}

func (o *GetLolLoadoutsV1LoadoutsReadyOK) Error() string {
	return fmt.Sprintf("[GET /lol-loadouts/v1/loadouts-ready][%d] getLolLoadoutsV1LoadoutsReadyOK  %+v", 200, o.Payload)
}

func (o *GetLolLoadoutsV1LoadoutsReadyOK) GetPayload() bool {
	return o.Payload
}

func (o *GetLolLoadoutsV1LoadoutsReadyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
