// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolRankedV1SignedRankedStatsReader is a Reader for the GetLolRankedV1SignedRankedStats structure.
type GetLolRankedV1SignedRankedStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolRankedV1SignedRankedStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolRankedV1SignedRankedStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolRankedV1SignedRankedStatsOK creates a GetLolRankedV1SignedRankedStatsOK with default headers values
func NewGetLolRankedV1SignedRankedStatsOK() *GetLolRankedV1SignedRankedStatsOK {
	return &GetLolRankedV1SignedRankedStatsOK{}
}

/*GetLolRankedV1SignedRankedStatsOK handles this case with default header values.

Successful response
*/
type GetLolRankedV1SignedRankedStatsOK struct {
	Payload *models.SignedRankedStatsDTO
}

func (o *GetLolRankedV1SignedRankedStatsOK) Error() string {
	return fmt.Sprintf("[GET /lol-ranked/v1/signed-ranked-stats][%d] getLolRankedV1SignedRankedStatsOK  %+v", 200, o.Payload)
}

func (o *GetLolRankedV1SignedRankedStatsOK) GetPayload() *models.SignedRankedStatsDTO {
	return o.Payload
}

func (o *GetLolRankedV1SignedRankedStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SignedRankedStatsDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
