// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolChatV1ConversationsByIDParticipantsReader is a Reader for the GetLolChatV1ConversationsByIDParticipants structure.
type GetLolChatV1ConversationsByIDParticipantsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolChatV1ConversationsByIDParticipantsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolChatV1ConversationsByIDParticipantsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolChatV1ConversationsByIDParticipantsOK creates a GetLolChatV1ConversationsByIDParticipantsOK with default headers values
func NewGetLolChatV1ConversationsByIDParticipantsOK() *GetLolChatV1ConversationsByIDParticipantsOK {
	return &GetLolChatV1ConversationsByIDParticipantsOK{}
}

/*GetLolChatV1ConversationsByIDParticipantsOK handles this case with default header values.

Successful response
*/
type GetLolChatV1ConversationsByIDParticipantsOK struct {
	Payload []*models.LolChatUserResource
}

func (o *GetLolChatV1ConversationsByIDParticipantsOK) Error() string {
	return fmt.Sprintf("[GET /lol-chat/v1/conversations/{id}/participants][%d] getLolChatV1ConversationsByIdParticipantsOK  %+v", 200, o.Payload)
}

func (o *GetLolChatV1ConversationsByIDParticipantsOK) GetPayload() []*models.LolChatUserResource {
	return o.Payload
}

func (o *GetLolChatV1ConversationsByIDParticipantsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
