// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolLootV1PlayerLootByLootIDContextMenuParams creates a new GetLolLootV1PlayerLootByLootIDContextMenuParams object
// with the default values initialized.
func NewGetLolLootV1PlayerLootByLootIDContextMenuParams() *GetLolLootV1PlayerLootByLootIDContextMenuParams {
	var ()
	return &GetLolLootV1PlayerLootByLootIDContextMenuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolLootV1PlayerLootByLootIDContextMenuParamsWithTimeout creates a new GetLolLootV1PlayerLootByLootIDContextMenuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolLootV1PlayerLootByLootIDContextMenuParamsWithTimeout(timeout time.Duration) *GetLolLootV1PlayerLootByLootIDContextMenuParams {
	var ()
	return &GetLolLootV1PlayerLootByLootIDContextMenuParams{

		timeout: timeout,
	}
}

// NewGetLolLootV1PlayerLootByLootIDContextMenuParamsWithContext creates a new GetLolLootV1PlayerLootByLootIDContextMenuParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolLootV1PlayerLootByLootIDContextMenuParamsWithContext(ctx context.Context) *GetLolLootV1PlayerLootByLootIDContextMenuParams {
	var ()
	return &GetLolLootV1PlayerLootByLootIDContextMenuParams{

		Context: ctx,
	}
}

// NewGetLolLootV1PlayerLootByLootIDContextMenuParamsWithHTTPClient creates a new GetLolLootV1PlayerLootByLootIDContextMenuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolLootV1PlayerLootByLootIDContextMenuParamsWithHTTPClient(client *http.Client) *GetLolLootV1PlayerLootByLootIDContextMenuParams {
	var ()
	return &GetLolLootV1PlayerLootByLootIDContextMenuParams{
		HTTPClient: client,
	}
}

/*GetLolLootV1PlayerLootByLootIDContextMenuParams contains all the parameters to send to the API endpoint
for the get lol loot v1 player loot by loot Id context menu operation typically these are written to a http.Request
*/
type GetLolLootV1PlayerLootByLootIDContextMenuParams struct {

	/*LootID*/
	LootID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol loot v1 player loot by loot Id context menu params
func (o *GetLolLootV1PlayerLootByLootIDContextMenuParams) WithTimeout(timeout time.Duration) *GetLolLootV1PlayerLootByLootIDContextMenuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol loot v1 player loot by loot Id context menu params
func (o *GetLolLootV1PlayerLootByLootIDContextMenuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol loot v1 player loot by loot Id context menu params
func (o *GetLolLootV1PlayerLootByLootIDContextMenuParams) WithContext(ctx context.Context) *GetLolLootV1PlayerLootByLootIDContextMenuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol loot v1 player loot by loot Id context menu params
func (o *GetLolLootV1PlayerLootByLootIDContextMenuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol loot v1 player loot by loot Id context menu params
func (o *GetLolLootV1PlayerLootByLootIDContextMenuParams) WithHTTPClient(client *http.Client) *GetLolLootV1PlayerLootByLootIDContextMenuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol loot v1 player loot by loot Id context menu params
func (o *GetLolLootV1PlayerLootByLootIDContextMenuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLootID adds the lootID to the get lol loot v1 player loot by loot Id context menu params
func (o *GetLolLootV1PlayerLootByLootIDContextMenuParams) WithLootID(lootID string) *GetLolLootV1PlayerLootByLootIDContextMenuParams {
	o.SetLootID(lootID)
	return o
}

// SetLootID adds the lootId to the get lol loot v1 player loot by loot Id context menu params
func (o *GetLolLootV1PlayerLootByLootIDContextMenuParams) SetLootID(lootID string) {
	o.LootID = lootID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolLootV1PlayerLootByLootIDContextMenuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param lootId
	if err := r.SetPathParam("lootId", o.LootID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
