// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDReader is a Reader for the GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinID structure.
type GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK creates a GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK with default headers values
func NewGetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK() *GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK {
	return &GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK{}
}

/*GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK handles this case with default header values.

Successful response
*/
type GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK struct {
	Payload *models.LolCollectionsCollectionsWardSkin
}

func (o *GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK) Error() string {
	return fmt.Sprintf("[GET /lol-collections/v1/inventories/{summonerId}/ward-skins/{wardSkinId}][%d] getLolCollectionsV1InventoriesBySummonerIdWardSkinsByWardSkinIdOK  %+v", 200, o.Payload)
}

func (o *GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK) GetPayload() *models.LolCollectionsCollectionsWardSkin {
	return o.Payload
}

func (o *GetLolCollectionsV1InventoriesBySummonerIDWardSkinsByWardSkinIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolCollectionsCollectionsWardSkin)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
