// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolSettingsV2LocalByCategoryParams creates a new GetLolSettingsV2LocalByCategoryParams object
// with the default values initialized.
func NewGetLolSettingsV2LocalByCategoryParams() *GetLolSettingsV2LocalByCategoryParams {
	var ()
	return &GetLolSettingsV2LocalByCategoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolSettingsV2LocalByCategoryParamsWithTimeout creates a new GetLolSettingsV2LocalByCategoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolSettingsV2LocalByCategoryParamsWithTimeout(timeout time.Duration) *GetLolSettingsV2LocalByCategoryParams {
	var ()
	return &GetLolSettingsV2LocalByCategoryParams{

		timeout: timeout,
	}
}

// NewGetLolSettingsV2LocalByCategoryParamsWithContext creates a new GetLolSettingsV2LocalByCategoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolSettingsV2LocalByCategoryParamsWithContext(ctx context.Context) *GetLolSettingsV2LocalByCategoryParams {
	var ()
	return &GetLolSettingsV2LocalByCategoryParams{

		Context: ctx,
	}
}

// NewGetLolSettingsV2LocalByCategoryParamsWithHTTPClient creates a new GetLolSettingsV2LocalByCategoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolSettingsV2LocalByCategoryParamsWithHTTPClient(client *http.Client) *GetLolSettingsV2LocalByCategoryParams {
	var ()
	return &GetLolSettingsV2LocalByCategoryParams{
		HTTPClient: client,
	}
}

/*GetLolSettingsV2LocalByCategoryParams contains all the parameters to send to the API endpoint
for the get lol settings v2 local by category operation typically these are written to a http.Request
*/
type GetLolSettingsV2LocalByCategoryParams struct {

	/*Category*/
	Category string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol settings v2 local by category params
func (o *GetLolSettingsV2LocalByCategoryParams) WithTimeout(timeout time.Duration) *GetLolSettingsV2LocalByCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol settings v2 local by category params
func (o *GetLolSettingsV2LocalByCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol settings v2 local by category params
func (o *GetLolSettingsV2LocalByCategoryParams) WithContext(ctx context.Context) *GetLolSettingsV2LocalByCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol settings v2 local by category params
func (o *GetLolSettingsV2LocalByCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol settings v2 local by category params
func (o *GetLolSettingsV2LocalByCategoryParams) WithHTTPClient(client *http.Client) *GetLolSettingsV2LocalByCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol settings v2 local by category params
func (o *GetLolSettingsV2LocalByCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the get lol settings v2 local by category params
func (o *GetLolSettingsV2LocalByCategoryParams) WithCategory(category string) *GetLolSettingsV2LocalByCategoryParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the get lol settings v2 local by category params
func (o *GetLolSettingsV2LocalByCategoryParams) SetCategory(category string) {
	o.Category = category
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolSettingsV2LocalByCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param category
	if err := r.SetPathParam("category", o.Category); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
