// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolSummonerV2SummonerIconsParams creates a new GetLolSummonerV2SummonerIconsParams object
// with the default values initialized.
func NewGetLolSummonerV2SummonerIconsParams() *GetLolSummonerV2SummonerIconsParams {
	var ()
	return &GetLolSummonerV2SummonerIconsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolSummonerV2SummonerIconsParamsWithTimeout creates a new GetLolSummonerV2SummonerIconsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolSummonerV2SummonerIconsParamsWithTimeout(timeout time.Duration) *GetLolSummonerV2SummonerIconsParams {
	var ()
	return &GetLolSummonerV2SummonerIconsParams{

		timeout: timeout,
	}
}

// NewGetLolSummonerV2SummonerIconsParamsWithContext creates a new GetLolSummonerV2SummonerIconsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolSummonerV2SummonerIconsParamsWithContext(ctx context.Context) *GetLolSummonerV2SummonerIconsParams {
	var ()
	return &GetLolSummonerV2SummonerIconsParams{

		Context: ctx,
	}
}

// NewGetLolSummonerV2SummonerIconsParamsWithHTTPClient creates a new GetLolSummonerV2SummonerIconsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolSummonerV2SummonerIconsParamsWithHTTPClient(client *http.Client) *GetLolSummonerV2SummonerIconsParams {
	var ()
	return &GetLolSummonerV2SummonerIconsParams{
		HTTPClient: client,
	}
}

/*GetLolSummonerV2SummonerIconsParams contains all the parameters to send to the API endpoint
for the get lol summoner v2 summoner icons operation typically these are written to a http.Request
*/
type GetLolSummonerV2SummonerIconsParams struct {

	/*Ids*/
	Ids []int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol summoner v2 summoner icons params
func (o *GetLolSummonerV2SummonerIconsParams) WithTimeout(timeout time.Duration) *GetLolSummonerV2SummonerIconsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol summoner v2 summoner icons params
func (o *GetLolSummonerV2SummonerIconsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol summoner v2 summoner icons params
func (o *GetLolSummonerV2SummonerIconsParams) WithContext(ctx context.Context) *GetLolSummonerV2SummonerIconsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol summoner v2 summoner icons params
func (o *GetLolSummonerV2SummonerIconsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol summoner v2 summoner icons params
func (o *GetLolSummonerV2SummonerIconsParams) WithHTTPClient(client *http.Client) *GetLolSummonerV2SummonerIconsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol summoner v2 summoner icons params
func (o *GetLolSummonerV2SummonerIconsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIds adds the ids to the get lol summoner v2 summoner icons params
func (o *GetLolSummonerV2SummonerIconsParams) WithIds(ids []int64) *GetLolSummonerV2SummonerIconsParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the get lol summoner v2 summoner icons params
func (o *GetLolSummonerV2SummonerIconsParams) SetIds(ids []int64) {
	o.Ids = ids
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolSummonerV2SummonerIconsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	var valuesIds []string
	for _, v := range o.Ids {
		valuesIds = append(valuesIds, swag.FormatInt64(v))
	}

	joinedIds := swag.JoinByFormat(valuesIds, "")
	// query array param ids
	if err := r.SetQueryParam("ids", joinedIds...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
