// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolStatstonesV1ProfileSummaryByPuuidReader is a Reader for the GetLolStatstonesV1ProfileSummaryByPuuid structure.
type GetLolStatstonesV1ProfileSummaryByPuuidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolStatstonesV1ProfileSummaryByPuuidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolStatstonesV1ProfileSummaryByPuuidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolStatstonesV1ProfileSummaryByPuuidOK creates a GetLolStatstonesV1ProfileSummaryByPuuidOK with default headers values
func NewGetLolStatstonesV1ProfileSummaryByPuuidOK() *GetLolStatstonesV1ProfileSummaryByPuuidOK {
	return &GetLolStatstonesV1ProfileSummaryByPuuidOK{}
}

/*GetLolStatstonesV1ProfileSummaryByPuuidOK handles this case with default header values.

Successful response
*/
type GetLolStatstonesV1ProfileSummaryByPuuidOK struct {
	Payload []*models.LolStatstonesProfileStatstoneSummary
}

func (o *GetLolStatstonesV1ProfileSummaryByPuuidOK) Error() string {
	return fmt.Sprintf("[GET /lol-statstones/v1/profile-summary/{puuid}][%d] getLolStatstonesV1ProfileSummaryByPuuidOK  %+v", 200, o.Payload)
}

func (o *GetLolStatstonesV1ProfileSummaryByPuuidOK) GetPayload() []*models.LolStatstonesProfileStatstoneSummary {
	return o.Payload
}

func (o *GetLolStatstonesV1ProfileSummaryByPuuidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
