// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolMapsV2MapByIDByGameModeByGameMutatorReader is a Reader for the GetLolMapsV2MapByIDByGameModeByGameMutator structure.
type GetLolMapsV2MapByIDByGameModeByGameMutatorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolMapsV2MapByIDByGameModeByGameMutatorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolMapsV2MapByIDByGameModeByGameMutatorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolMapsV2MapByIDByGameModeByGameMutatorOK creates a GetLolMapsV2MapByIDByGameModeByGameMutatorOK with default headers values
func NewGetLolMapsV2MapByIDByGameModeByGameMutatorOK() *GetLolMapsV2MapByIDByGameModeByGameMutatorOK {
	return &GetLolMapsV2MapByIDByGameModeByGameMutatorOK{}
}

/*GetLolMapsV2MapByIDByGameModeByGameMutatorOK handles this case with default header values.

Successful response
*/
type GetLolMapsV2MapByIDByGameModeByGameMutatorOK struct {
	Payload *models.LolMapsMaps
}

func (o *GetLolMapsV2MapByIDByGameModeByGameMutatorOK) Error() string {
	return fmt.Sprintf("[GET /lol-maps/v2/map/{id}/{gameMode}/{gameMutator}][%d] getLolMapsV2MapByIdByGameModeByGameMutatorOK  %+v", 200, o.Payload)
}

func (o *GetLolMapsV2MapByIDByGameModeByGameMutatorOK) GetPayload() *models.LolMapsMaps {
	return o.Payload
}

func (o *GetLolMapsV2MapByIDByGameModeByGameMutatorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolMapsMaps)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
