// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolRankedV1SplitsConfigReader is a Reader for the GetLolRankedV1SplitsConfig structure.
type GetLolRankedV1SplitsConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolRankedV1SplitsConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolRankedV1SplitsConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolRankedV1SplitsConfigOK creates a GetLolRankedV1SplitsConfigOK with default headers values
func NewGetLolRankedV1SplitsConfigOK() *GetLolRankedV1SplitsConfigOK {
	return &GetLolRankedV1SplitsConfigOK{}
}

/*GetLolRankedV1SplitsConfigOK handles this case with default header values.

Successful response
*/
type GetLolRankedV1SplitsConfigOK struct {
	Payload *models.LolRankedRewardsInfo
}

func (o *GetLolRankedV1SplitsConfigOK) Error() string {
	return fmt.Sprintf("[GET /lol-ranked/v1/splits-config][%d] getLolRankedV1SplitsConfigOK  %+v", 200, o.Payload)
}

func (o *GetLolRankedV1SplitsConfigOK) GetPayload() *models.LolRankedRewardsInfo {
	return o.Payload
}

func (o *GetLolRankedV1SplitsConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolRankedRewardsInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
