// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetLolClashV1CurrentTournamentIdsReader is a Reader for the GetLolClashV1CurrentTournamentIds structure.
type GetLolClashV1CurrentTournamentIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolClashV1CurrentTournamentIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolClashV1CurrentTournamentIdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolClashV1CurrentTournamentIdsOK creates a GetLolClashV1CurrentTournamentIdsOK with default headers values
func NewGetLolClashV1CurrentTournamentIdsOK() *GetLolClashV1CurrentTournamentIdsOK {
	return &GetLolClashV1CurrentTournamentIdsOK{}
}

/*GetLolClashV1CurrentTournamentIdsOK handles this case with default header values.

Successful response
*/
type GetLolClashV1CurrentTournamentIdsOK struct {
	Payload []int64
}

func (o *GetLolClashV1CurrentTournamentIdsOK) Error() string {
	return fmt.Sprintf("[GET /lol-clash/v1/currentTournamentIds][%d] getLolClashV1CurrentTournamentIdsOK  %+v", 200, o.Payload)
}

func (o *GetLolClashV1CurrentTournamentIdsOK) GetPayload() []int64 {
	return o.Payload
}

func (o *GetLolClashV1CurrentTournamentIdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
