// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolGameflowV1EarlyExitNotificationsMissionsParams creates a new GetLolGameflowV1EarlyExitNotificationsMissionsParams object
// with the default values initialized.
func NewGetLolGameflowV1EarlyExitNotificationsMissionsParams() *GetLolGameflowV1EarlyExitNotificationsMissionsParams {

	return &GetLolGameflowV1EarlyExitNotificationsMissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolGameflowV1EarlyExitNotificationsMissionsParamsWithTimeout creates a new GetLolGameflowV1EarlyExitNotificationsMissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolGameflowV1EarlyExitNotificationsMissionsParamsWithTimeout(timeout time.Duration) *GetLolGameflowV1EarlyExitNotificationsMissionsParams {

	return &GetLolGameflowV1EarlyExitNotificationsMissionsParams{

		timeout: timeout,
	}
}

// NewGetLolGameflowV1EarlyExitNotificationsMissionsParamsWithContext creates a new GetLolGameflowV1EarlyExitNotificationsMissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolGameflowV1EarlyExitNotificationsMissionsParamsWithContext(ctx context.Context) *GetLolGameflowV1EarlyExitNotificationsMissionsParams {

	return &GetLolGameflowV1EarlyExitNotificationsMissionsParams{

		Context: ctx,
	}
}

// NewGetLolGameflowV1EarlyExitNotificationsMissionsParamsWithHTTPClient creates a new GetLolGameflowV1EarlyExitNotificationsMissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolGameflowV1EarlyExitNotificationsMissionsParamsWithHTTPClient(client *http.Client) *GetLolGameflowV1EarlyExitNotificationsMissionsParams {

	return &GetLolGameflowV1EarlyExitNotificationsMissionsParams{
		HTTPClient: client,
	}
}

/*GetLolGameflowV1EarlyExitNotificationsMissionsParams contains all the parameters to send to the API endpoint
for the get lol gameflow v1 early exit notifications missions operation typically these are written to a http.Request
*/
type GetLolGameflowV1EarlyExitNotificationsMissionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol gameflow v1 early exit notifications missions params
func (o *GetLolGameflowV1EarlyExitNotificationsMissionsParams) WithTimeout(timeout time.Duration) *GetLolGameflowV1EarlyExitNotificationsMissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol gameflow v1 early exit notifications missions params
func (o *GetLolGameflowV1EarlyExitNotificationsMissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol gameflow v1 early exit notifications missions params
func (o *GetLolGameflowV1EarlyExitNotificationsMissionsParams) WithContext(ctx context.Context) *GetLolGameflowV1EarlyExitNotificationsMissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol gameflow v1 early exit notifications missions params
func (o *GetLolGameflowV1EarlyExitNotificationsMissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol gameflow v1 early exit notifications missions params
func (o *GetLolGameflowV1EarlyExitNotificationsMissionsParams) WithHTTPClient(client *http.Client) *GetLolGameflowV1EarlyExitNotificationsMissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol gameflow v1 early exit notifications missions params
func (o *GetLolGameflowV1EarlyExitNotificationsMissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolGameflowV1EarlyExitNotificationsMissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
