// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolChampSelectV1AllGridChampionsReader is a Reader for the GetLolChampSelectV1AllGridChampions structure.
type GetLolChampSelectV1AllGridChampionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolChampSelectV1AllGridChampionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolChampSelectV1AllGridChampionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolChampSelectV1AllGridChampionsOK creates a GetLolChampSelectV1AllGridChampionsOK with default headers values
func NewGetLolChampSelectV1AllGridChampionsOK() *GetLolChampSelectV1AllGridChampionsOK {
	return &GetLolChampSelectV1AllGridChampionsOK{}
}

/*GetLolChampSelectV1AllGridChampionsOK handles this case with default header values.

Successful response
*/
type GetLolChampSelectV1AllGridChampionsOK struct {
	Payload []*models.LolChampSelectChampGridChampion
}

func (o *GetLolChampSelectV1AllGridChampionsOK) Error() string {
	return fmt.Sprintf("[GET /lol-champ-select/v1/all-grid-champions][%d] getLolChampSelectV1AllGridChampionsOK  %+v", 200, o.Payload)
}

func (o *GetLolChampSelectV1AllGridChampionsOK) GetPayload() []*models.LolChampSelectChampGridChampion {
	return o.Payload
}

func (o *GetLolChampSelectV1AllGridChampionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
