// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolInventoryV1NotificationsByInventoryTypeParams creates a new GetLolInventoryV1NotificationsByInventoryTypeParams object
// with the default values initialized.
func NewGetLolInventoryV1NotificationsByInventoryTypeParams() *GetLolInventoryV1NotificationsByInventoryTypeParams {
	var ()
	return &GetLolInventoryV1NotificationsByInventoryTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolInventoryV1NotificationsByInventoryTypeParamsWithTimeout creates a new GetLolInventoryV1NotificationsByInventoryTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolInventoryV1NotificationsByInventoryTypeParamsWithTimeout(timeout time.Duration) *GetLolInventoryV1NotificationsByInventoryTypeParams {
	var ()
	return &GetLolInventoryV1NotificationsByInventoryTypeParams{

		timeout: timeout,
	}
}

// NewGetLolInventoryV1NotificationsByInventoryTypeParamsWithContext creates a new GetLolInventoryV1NotificationsByInventoryTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolInventoryV1NotificationsByInventoryTypeParamsWithContext(ctx context.Context) *GetLolInventoryV1NotificationsByInventoryTypeParams {
	var ()
	return &GetLolInventoryV1NotificationsByInventoryTypeParams{

		Context: ctx,
	}
}

// NewGetLolInventoryV1NotificationsByInventoryTypeParamsWithHTTPClient creates a new GetLolInventoryV1NotificationsByInventoryTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolInventoryV1NotificationsByInventoryTypeParamsWithHTTPClient(client *http.Client) *GetLolInventoryV1NotificationsByInventoryTypeParams {
	var ()
	return &GetLolInventoryV1NotificationsByInventoryTypeParams{
		HTTPClient: client,
	}
}

/*GetLolInventoryV1NotificationsByInventoryTypeParams contains all the parameters to send to the API endpoint
for the get lol inventory v1 notifications by inventory type operation typically these are written to a http.Request
*/
type GetLolInventoryV1NotificationsByInventoryTypeParams struct {

	/*InventoryType*/
	InventoryType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol inventory v1 notifications by inventory type params
func (o *GetLolInventoryV1NotificationsByInventoryTypeParams) WithTimeout(timeout time.Duration) *GetLolInventoryV1NotificationsByInventoryTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol inventory v1 notifications by inventory type params
func (o *GetLolInventoryV1NotificationsByInventoryTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol inventory v1 notifications by inventory type params
func (o *GetLolInventoryV1NotificationsByInventoryTypeParams) WithContext(ctx context.Context) *GetLolInventoryV1NotificationsByInventoryTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol inventory v1 notifications by inventory type params
func (o *GetLolInventoryV1NotificationsByInventoryTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol inventory v1 notifications by inventory type params
func (o *GetLolInventoryV1NotificationsByInventoryTypeParams) WithHTTPClient(client *http.Client) *GetLolInventoryV1NotificationsByInventoryTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol inventory v1 notifications by inventory type params
func (o *GetLolInventoryV1NotificationsByInventoryTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInventoryType adds the inventoryType to the get lol inventory v1 notifications by inventory type params
func (o *GetLolInventoryV1NotificationsByInventoryTypeParams) WithInventoryType(inventoryType string) *GetLolInventoryV1NotificationsByInventoryTypeParams {
	o.SetInventoryType(inventoryType)
	return o
}

// SetInventoryType adds the inventoryType to the get lol inventory v1 notifications by inventory type params
func (o *GetLolInventoryV1NotificationsByInventoryTypeParams) SetInventoryType(inventoryType string) {
	o.InventoryType = inventoryType
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolInventoryV1NotificationsByInventoryTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inventoryType
	if err := r.SetPathParam("inventoryType", o.InventoryType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
