// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolGameflowV1SpectateParams creates a new GetLolGameflowV1SpectateParams object
// with the default values initialized.
func NewGetLolGameflowV1SpectateParams() *GetLolGameflowV1SpectateParams {

	return &GetLolGameflowV1SpectateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolGameflowV1SpectateParamsWithTimeout creates a new GetLolGameflowV1SpectateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolGameflowV1SpectateParamsWithTimeout(timeout time.Duration) *GetLolGameflowV1SpectateParams {

	return &GetLolGameflowV1SpectateParams{

		timeout: timeout,
	}
}

// NewGetLolGameflowV1SpectateParamsWithContext creates a new GetLolGameflowV1SpectateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolGameflowV1SpectateParamsWithContext(ctx context.Context) *GetLolGameflowV1SpectateParams {

	return &GetLolGameflowV1SpectateParams{

		Context: ctx,
	}
}

// NewGetLolGameflowV1SpectateParamsWithHTTPClient creates a new GetLolGameflowV1SpectateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolGameflowV1SpectateParamsWithHTTPClient(client *http.Client) *GetLolGameflowV1SpectateParams {

	return &GetLolGameflowV1SpectateParams{
		HTTPClient: client,
	}
}

/*GetLolGameflowV1SpectateParams contains all the parameters to send to the API endpoint
for the get lol gameflow v1 spectate operation typically these are written to a http.Request
*/
type GetLolGameflowV1SpectateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol gameflow v1 spectate params
func (o *GetLolGameflowV1SpectateParams) WithTimeout(timeout time.Duration) *GetLolGameflowV1SpectateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol gameflow v1 spectate params
func (o *GetLolGameflowV1SpectateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol gameflow v1 spectate params
func (o *GetLolGameflowV1SpectateParams) WithContext(ctx context.Context) *GetLolGameflowV1SpectateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol gameflow v1 spectate params
func (o *GetLolGameflowV1SpectateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol gameflow v1 spectate params
func (o *GetLolGameflowV1SpectateParams) WithHTTPClient(client *http.Client) *GetLolGameflowV1SpectateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol gameflow v1 spectate params
func (o *GetLolGameflowV1SpectateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolGameflowV1SpectateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
