// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams creates a new GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams object
// with the default values initialized.
func NewGetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams() *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	var ()
	return &GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParamsWithTimeout creates a new GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParamsWithTimeout(timeout time.Duration) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	var ()
	return &GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams{

		timeout: timeout,
	}
}

// NewGetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParamsWithContext creates a new GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParamsWithContext(ctx context.Context) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	var ()
	return &GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams{

		Context: ctx,
	}
}

// NewGetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParamsWithHTTPClient creates a new GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParamsWithHTTPClient(client *http.Client) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	var ()
	return &GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams{
		HTTPClient: client,
	}
}

/*GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams contains all the parameters to send to the API endpoint
for the get lol career stats v1 champion averages by champion Id by position by tier by queue operation typically these are written to a http.Request
*/
type GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams struct {

	/*ChampionID*/
	ChampionID int32
	/*Position*/
	Position string
	/*Queue*/
	Queue string
	/*Tier*/
	Tier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) WithTimeout(timeout time.Duration) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) WithContext(ctx context.Context) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) WithHTTPClient(client *http.Client) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChampionID adds the championID to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) WithChampionID(championID int32) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	o.SetChampionID(championID)
	return o
}

// SetChampionID adds the championId to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) SetChampionID(championID int32) {
	o.ChampionID = championID
}

// WithPosition adds the position to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) WithPosition(position string) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	o.SetPosition(position)
	return o
}

// SetPosition adds the position to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) SetPosition(position string) {
	o.Position = position
}

// WithQueue adds the queue to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) WithQueue(queue string) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	o.SetQueue(queue)
	return o
}

// SetQueue adds the queue to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) SetQueue(queue string) {
	o.Queue = queue
}

// WithTier adds the tier to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) WithTier(tier string) *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams {
	o.SetTier(tier)
	return o
}

// SetTier adds the tier to the get lol career stats v1 champion averages by champion Id by position by tier by queue params
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) SetTier(tier string) {
	o.Tier = tier
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolCareerStatsV1ChampionAveragesByChampionIDByPositionByTierByQueueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param championId
	if err := r.SetPathParam("championId", swag.FormatInt32(o.ChampionID)); err != nil {
		return err
	}

	// path param position
	if err := r.SetPathParam("position", o.Position); err != nil {
		return err
	}

	// path param queue
	if err := r.SetPathParam("queue", o.Queue); err != nil {
		return err
	}

	// path param tier
	if err := r.SetPathParam("tier", o.Tier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
