// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetLolMatchHistoryV1WebURLReader is a Reader for the GetLolMatchHistoryV1WebURL structure.
type GetLolMatchHistoryV1WebURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolMatchHistoryV1WebURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolMatchHistoryV1WebURLOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolMatchHistoryV1WebURLOK creates a GetLolMatchHistoryV1WebURLOK with default headers values
func NewGetLolMatchHistoryV1WebURLOK() *GetLolMatchHistoryV1WebURLOK {
	return &GetLolMatchHistoryV1WebURLOK{}
}

/*GetLolMatchHistoryV1WebURLOK handles this case with default header values.

Successful response
*/
type GetLolMatchHistoryV1WebURLOK struct {
	Payload string
}

func (o *GetLolMatchHistoryV1WebURLOK) Error() string {
	return fmt.Sprintf("[GET /lol-match-history/v1/web-url][%d] getLolMatchHistoryV1WebUrlOK  %+v", 200, o.Payload)
}

func (o *GetLolMatchHistoryV1WebURLOK) GetPayload() string {
	return o.Payload
}

func (o *GetLolMatchHistoryV1WebURLOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
