// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolClashV1ScoutingChampionsReader is a Reader for the GetLolClashV1ScoutingChampions structure.
type GetLolClashV1ScoutingChampionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolClashV1ScoutingChampionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolClashV1ScoutingChampionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolClashV1ScoutingChampionsOK creates a GetLolClashV1ScoutingChampionsOK with default headers values
func NewGetLolClashV1ScoutingChampionsOK() *GetLolClashV1ScoutingChampionsOK {
	return &GetLolClashV1ScoutingChampionsOK{}
}

/*GetLolClashV1ScoutingChampionsOK handles this case with default header values.

Successful response
*/
type GetLolClashV1ScoutingChampionsOK struct {
	Payload []*models.LolClashScoutingChampions
}

func (o *GetLolClashV1ScoutingChampionsOK) Error() string {
	return fmt.Sprintf("[GET /lol-clash/v1/scouting/champions][%d] getLolClashV1ScoutingChampionsOK  %+v", 200, o.Payload)
}

func (o *GetLolClashV1ScoutingChampionsOK) GetPayload() []*models.LolClashScoutingChampions {
	return o.Payload
}

func (o *GetLolClashV1ScoutingChampionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
