// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetLolLootV1ReadyReader is a Reader for the GetLolLootV1Ready structure.
type GetLolLootV1ReadyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolLootV1ReadyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolLootV1ReadyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolLootV1ReadyOK creates a GetLolLootV1ReadyOK with default headers values
func NewGetLolLootV1ReadyOK() *GetLolLootV1ReadyOK {
	return &GetLolLootV1ReadyOK{}
}

/*GetLolLootV1ReadyOK handles this case with default header values.

Successful response
*/
type GetLolLootV1ReadyOK struct {
	Payload bool
}

func (o *GetLolLootV1ReadyOK) Error() string {
	return fmt.Sprintf("[GET /lol-loot/v1/ready][%d] getLolLootV1ReadyOK  %+v", 200, o.Payload)
}

func (o *GetLolLootV1ReadyOK) GetPayload() bool {
	return o.Payload
}

func (o *GetLolLootV1ReadyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
