// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountReader is a Reader for the GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCount structure.
type GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK creates a GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK with default headers values
func NewGetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK() *GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK {
	return &GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK{}
}

/*GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK handles this case with default header values.

Successful response
*/
type GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK struct {
	Payload *models.LolChampionsCollectionsChampionPlayableCounts
}

func (o *GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK) Error() string {
	return fmt.Sprintf("[GET /lol-champions/v1/inventories/{summonerId}/champions-playable-count][%d] getLolChampionsV1InventoriesBySummonerIdChampionsPlayableCountOK  %+v", 200, o.Payload)
}

func (o *GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK) GetPayload() *models.LolChampionsCollectionsChampionPlayableCounts {
	return o.Payload
}

func (o *GetLolChampionsV1InventoriesBySummonerIDChampionsPlayableCountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolChampionsCollectionsChampionPlayableCounts)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
