// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetLolClashV1TournamentGetAllPlayerTiersReader is a Reader for the GetLolClashV1TournamentGetAllPlayerTiers structure.
type GetLolClashV1TournamentGetAllPlayerTiersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLolClashV1TournamentGetAllPlayerTiersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLolClashV1TournamentGetAllPlayerTiersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLolClashV1TournamentGetAllPlayerTiersOK creates a GetLolClashV1TournamentGetAllPlayerTiersOK with default headers values
func NewGetLolClashV1TournamentGetAllPlayerTiersOK() *GetLolClashV1TournamentGetAllPlayerTiersOK {
	return &GetLolClashV1TournamentGetAllPlayerTiersOK{}
}

/*GetLolClashV1TournamentGetAllPlayerTiersOK handles this case with default header values.

Successful response
*/
type GetLolClashV1TournamentGetAllPlayerTiersOK struct {
	Payload []*models.PlayerTierDTO
}

func (o *GetLolClashV1TournamentGetAllPlayerTiersOK) Error() string {
	return fmt.Sprintf("[GET /lol-clash/v1/tournament/get-all-player-tiers][%d] getLolClashV1TournamentGetAllPlayerTiersOK  %+v", 200, o.Payload)
}

func (o *GetLolClashV1TournamentGetAllPlayerTiersOK) GetPayload() []*models.PlayerTierDTO {
	return o.Payload
}

func (o *GetLolClashV1TournamentGetAllPlayerTiersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
