// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// GetRecofrienderV2DismissedPageReader is a Reader for the GetRecofrienderV2DismissedPage structure.
type GetRecofrienderV2DismissedPageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRecofrienderV2DismissedPageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRecofrienderV2DismissedPageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRecofrienderV2DismissedPageOK creates a GetRecofrienderV2DismissedPageOK with default headers values
func NewGetRecofrienderV2DismissedPageOK() *GetRecofrienderV2DismissedPageOK {
	return &GetRecofrienderV2DismissedPageOK{}
}

/*GetRecofrienderV2DismissedPageOK handles this case with default header values.

Successful response
*/
type GetRecofrienderV2DismissedPageOK struct {
	Payload *models.RecofrienderContactPaginationResource
}

func (o *GetRecofrienderV2DismissedPageOK) Error() string {
	return fmt.Sprintf("[GET /recofriender/v2/dismissed/page][%d] getRecofrienderV2DismissedPageOK  %+v", 200, o.Payload)
}

func (o *GetRecofrienderV2DismissedPageOK) GetPayload() *models.RecofrienderContactPaginationResource {
	return o.Payload
}

func (o *GetRecofrienderV2DismissedPageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RecofrienderContactPaginationResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
