// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolRsoAuthV1AuthHintsHintParams creates a new GetLolRsoAuthV1AuthHintsHintParams object
// with the default values initialized.
func NewGetLolRsoAuthV1AuthHintsHintParams() *GetLolRsoAuthV1AuthHintsHintParams {

	return &GetLolRsoAuthV1AuthHintsHintParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolRsoAuthV1AuthHintsHintParamsWithTimeout creates a new GetLolRsoAuthV1AuthHintsHintParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolRsoAuthV1AuthHintsHintParamsWithTimeout(timeout time.Duration) *GetLolRsoAuthV1AuthHintsHintParams {

	return &GetLolRsoAuthV1AuthHintsHintParams{

		timeout: timeout,
	}
}

// NewGetLolRsoAuthV1AuthHintsHintParamsWithContext creates a new GetLolRsoAuthV1AuthHintsHintParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolRsoAuthV1AuthHintsHintParamsWithContext(ctx context.Context) *GetLolRsoAuthV1AuthHintsHintParams {

	return &GetLolRsoAuthV1AuthHintsHintParams{

		Context: ctx,
	}
}

// NewGetLolRsoAuthV1AuthHintsHintParamsWithHTTPClient creates a new GetLolRsoAuthV1AuthHintsHintParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolRsoAuthV1AuthHintsHintParamsWithHTTPClient(client *http.Client) *GetLolRsoAuthV1AuthHintsHintParams {

	return &GetLolRsoAuthV1AuthHintsHintParams{
		HTTPClient: client,
	}
}

/*GetLolRsoAuthV1AuthHintsHintParams contains all the parameters to send to the API endpoint
for the get lol rso auth v1 auth hints hint operation typically these are written to a http.Request
*/
type GetLolRsoAuthV1AuthHintsHintParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol rso auth v1 auth hints hint params
func (o *GetLolRsoAuthV1AuthHintsHintParams) WithTimeout(timeout time.Duration) *GetLolRsoAuthV1AuthHintsHintParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol rso auth v1 auth hints hint params
func (o *GetLolRsoAuthV1AuthHintsHintParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol rso auth v1 auth hints hint params
func (o *GetLolRsoAuthV1AuthHintsHintParams) WithContext(ctx context.Context) *GetLolRsoAuthV1AuthHintsHintParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol rso auth v1 auth hints hint params
func (o *GetLolRsoAuthV1AuthHintsHintParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol rso auth v1 auth hints hint params
func (o *GetLolRsoAuthV1AuthHintsHintParams) WithHTTPClient(client *http.Client) *GetLolRsoAuthV1AuthHintsHintParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol rso auth v1 auth hints hint params
func (o *GetLolRsoAuthV1AuthHintsHintParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolRsoAuthV1AuthHintsHintParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
