// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLolPerksV1SchemaVersionParams creates a new GetLolPerksV1SchemaVersionParams object
// with the default values initialized.
func NewGetLolPerksV1SchemaVersionParams() *GetLolPerksV1SchemaVersionParams {

	return &GetLolPerksV1SchemaVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLolPerksV1SchemaVersionParamsWithTimeout creates a new GetLolPerksV1SchemaVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLolPerksV1SchemaVersionParamsWithTimeout(timeout time.Duration) *GetLolPerksV1SchemaVersionParams {

	return &GetLolPerksV1SchemaVersionParams{

		timeout: timeout,
	}
}

// NewGetLolPerksV1SchemaVersionParamsWithContext creates a new GetLolPerksV1SchemaVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLolPerksV1SchemaVersionParamsWithContext(ctx context.Context) *GetLolPerksV1SchemaVersionParams {

	return &GetLolPerksV1SchemaVersionParams{

		Context: ctx,
	}
}

// NewGetLolPerksV1SchemaVersionParamsWithHTTPClient creates a new GetLolPerksV1SchemaVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLolPerksV1SchemaVersionParamsWithHTTPClient(client *http.Client) *GetLolPerksV1SchemaVersionParams {

	return &GetLolPerksV1SchemaVersionParams{
		HTTPClient: client,
	}
}

/*GetLolPerksV1SchemaVersionParams contains all the parameters to send to the API endpoint
for the get lol perks v1 schema version operation typically these are written to a http.Request
*/
type GetLolPerksV1SchemaVersionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lol perks v1 schema version params
func (o *GetLolPerksV1SchemaVersionParams) WithTimeout(timeout time.Duration) *GetLolPerksV1SchemaVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lol perks v1 schema version params
func (o *GetLolPerksV1SchemaVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lol perks v1 schema version params
func (o *GetLolPerksV1SchemaVersionParams) WithContext(ctx context.Context) *GetLolPerksV1SchemaVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lol perks v1 schema version params
func (o *GetLolPerksV1SchemaVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lol perks v1 schema version params
func (o *GetLolPerksV1SchemaVersionParams) WithHTTPClient(client *http.Client) *GetLolPerksV1SchemaVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lol perks v1 schema version params
func (o *GetLolPerksV1SchemaVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLolPerksV1SchemaVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
