// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PatchLolGameSettingsV1InputSettingsReader is a Reader for the PatchLolGameSettingsV1InputSettings structure.
type PatchLolGameSettingsV1InputSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchLolGameSettingsV1InputSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchLolGameSettingsV1InputSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchLolGameSettingsV1InputSettingsOK creates a PatchLolGameSettingsV1InputSettingsOK with default headers values
func NewPatchLolGameSettingsV1InputSettingsOK() *PatchLolGameSettingsV1InputSettingsOK {
	return &PatchLolGameSettingsV1InputSettingsOK{}
}

/*PatchLolGameSettingsV1InputSettingsOK handles this case with default header values.

Successful response
*/
type PatchLolGameSettingsV1InputSettingsOK struct {
	Payload interface{}
}

func (o *PatchLolGameSettingsV1InputSettingsOK) Error() string {
	return fmt.Sprintf("[PATCH /lol-game-settings/v1/input-settings][%d] patchLolGameSettingsV1InputSettingsOK  %+v", 200, o.Payload)
}

func (o *PatchLolGameSettingsV1InputSettingsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PatchLolGameSettingsV1InputSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
