// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostLolPremadeVoiceV1FirstExperienceResetParams creates a new PostLolPremadeVoiceV1FirstExperienceResetParams object
// with the default values initialized.
func NewPostLolPremadeVoiceV1FirstExperienceResetParams() *PostLolPremadeVoiceV1FirstExperienceResetParams {

	return &PostLolPremadeVoiceV1FirstExperienceResetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLolPremadeVoiceV1FirstExperienceResetParamsWithTimeout creates a new PostLolPremadeVoiceV1FirstExperienceResetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLolPremadeVoiceV1FirstExperienceResetParamsWithTimeout(timeout time.Duration) *PostLolPremadeVoiceV1FirstExperienceResetParams {

	return &PostLolPremadeVoiceV1FirstExperienceResetParams{

		timeout: timeout,
	}
}

// NewPostLolPremadeVoiceV1FirstExperienceResetParamsWithContext creates a new PostLolPremadeVoiceV1FirstExperienceResetParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLolPremadeVoiceV1FirstExperienceResetParamsWithContext(ctx context.Context) *PostLolPremadeVoiceV1FirstExperienceResetParams {

	return &PostLolPremadeVoiceV1FirstExperienceResetParams{

		Context: ctx,
	}
}

// NewPostLolPremadeVoiceV1FirstExperienceResetParamsWithHTTPClient creates a new PostLolPremadeVoiceV1FirstExperienceResetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLolPremadeVoiceV1FirstExperienceResetParamsWithHTTPClient(client *http.Client) *PostLolPremadeVoiceV1FirstExperienceResetParams {

	return &PostLolPremadeVoiceV1FirstExperienceResetParams{
		HTTPClient: client,
	}
}

/*PostLolPremadeVoiceV1FirstExperienceResetParams contains all the parameters to send to the API endpoint
for the post lol premade voice v1 first experience reset operation typically these are written to a http.Request
*/
type PostLolPremadeVoiceV1FirstExperienceResetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post lol premade voice v1 first experience reset params
func (o *PostLolPremadeVoiceV1FirstExperienceResetParams) WithTimeout(timeout time.Duration) *PostLolPremadeVoiceV1FirstExperienceResetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post lol premade voice v1 first experience reset params
func (o *PostLolPremadeVoiceV1FirstExperienceResetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post lol premade voice v1 first experience reset params
func (o *PostLolPremadeVoiceV1FirstExperienceResetParams) WithContext(ctx context.Context) *PostLolPremadeVoiceV1FirstExperienceResetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post lol premade voice v1 first experience reset params
func (o *PostLolPremadeVoiceV1FirstExperienceResetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post lol premade voice v1 first experience reset params
func (o *PostLolPremadeVoiceV1FirstExperienceResetParams) WithHTTPClient(client *http.Client) *PostLolPremadeVoiceV1FirstExperienceResetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post lol premade voice v1 first experience reset params
func (o *PostLolPremadeVoiceV1FirstExperienceResetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostLolPremadeVoiceV1FirstExperienceResetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
