// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// PostPlayerNotificationsV1NotificationsReader is a Reader for the PostPlayerNotificationsV1Notifications structure.
type PostPlayerNotificationsV1NotificationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPlayerNotificationsV1NotificationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostPlayerNotificationsV1NotificationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostPlayerNotificationsV1NotificationsOK creates a PostPlayerNotificationsV1NotificationsOK with default headers values
func NewPostPlayerNotificationsV1NotificationsOK() *PostPlayerNotificationsV1NotificationsOK {
	return &PostPlayerNotificationsV1NotificationsOK{}
}

/*PostPlayerNotificationsV1NotificationsOK handles this case with default header values.

Successful response
*/
type PostPlayerNotificationsV1NotificationsOK struct {
	Payload *models.PlayerNotificationsPlayerNotificationResource
}

func (o *PostPlayerNotificationsV1NotificationsOK) Error() string {
	return fmt.Sprintf("[POST /player-notifications/v1/notifications][%d] postPlayerNotificationsV1NotificationsOK  %+v", 200, o.Payload)
}

func (o *PostPlayerNotificationsV1NotificationsOK) GetPayload() *models.PlayerNotificationsPlayerNotificationResource {
	return o.Payload
}

func (o *PostPlayerNotificationsV1NotificationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PlayerNotificationsPlayerNotificationResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
