// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLolPurchaseWidgetV1PurchaseItemsReader is a Reader for the PostLolPurchaseWidgetV1PurchaseItems structure.
type PostLolPurchaseWidgetV1PurchaseItemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLolPurchaseWidgetV1PurchaseItemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostLolPurchaseWidgetV1PurchaseItemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLolPurchaseWidgetV1PurchaseItemsOK creates a PostLolPurchaseWidgetV1PurchaseItemsOK with default headers values
func NewPostLolPurchaseWidgetV1PurchaseItemsOK() *PostLolPurchaseWidgetV1PurchaseItemsOK {
	return &PostLolPurchaseWidgetV1PurchaseItemsOK{}
}

/*PostLolPurchaseWidgetV1PurchaseItemsOK handles this case with default header values.

Successful response
*/
type PostLolPurchaseWidgetV1PurchaseItemsOK struct {
	Payload interface{}
}

func (o *PostLolPurchaseWidgetV1PurchaseItemsOK) Error() string {
	return fmt.Sprintf("[POST /lol-purchase-widget/v1/purchaseItems][%d] postLolPurchaseWidgetV1PurchaseItemsOK  %+v", 200, o.Payload)
}

func (o *PostLolPurchaseWidgetV1PurchaseItemsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PostLolPurchaseWidgetV1PurchaseItemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
