// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostLolChampSelectV1SessionMySelectionRerollParams creates a new PostLolChampSelectV1SessionMySelectionRerollParams object
// with the default values initialized.
func NewPostLolChampSelectV1SessionMySelectionRerollParams() *PostLolChampSelectV1SessionMySelectionRerollParams {

	return &PostLolChampSelectV1SessionMySelectionRerollParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLolChampSelectV1SessionMySelectionRerollParamsWithTimeout creates a new PostLolChampSelectV1SessionMySelectionRerollParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLolChampSelectV1SessionMySelectionRerollParamsWithTimeout(timeout time.Duration) *PostLolChampSelectV1SessionMySelectionRerollParams {

	return &PostLolChampSelectV1SessionMySelectionRerollParams{

		timeout: timeout,
	}
}

// NewPostLolChampSelectV1SessionMySelectionRerollParamsWithContext creates a new PostLolChampSelectV1SessionMySelectionRerollParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLolChampSelectV1SessionMySelectionRerollParamsWithContext(ctx context.Context) *PostLolChampSelectV1SessionMySelectionRerollParams {

	return &PostLolChampSelectV1SessionMySelectionRerollParams{

		Context: ctx,
	}
}

// NewPostLolChampSelectV1SessionMySelectionRerollParamsWithHTTPClient creates a new PostLolChampSelectV1SessionMySelectionRerollParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLolChampSelectV1SessionMySelectionRerollParamsWithHTTPClient(client *http.Client) *PostLolChampSelectV1SessionMySelectionRerollParams {

	return &PostLolChampSelectV1SessionMySelectionRerollParams{
		HTTPClient: client,
	}
}

/*PostLolChampSelectV1SessionMySelectionRerollParams contains all the parameters to send to the API endpoint
for the post lol champ select v1 session my selection reroll operation typically these are written to a http.Request
*/
type PostLolChampSelectV1SessionMySelectionRerollParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post lol champ select v1 session my selection reroll params
func (o *PostLolChampSelectV1SessionMySelectionRerollParams) WithTimeout(timeout time.Duration) *PostLolChampSelectV1SessionMySelectionRerollParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post lol champ select v1 session my selection reroll params
func (o *PostLolChampSelectV1SessionMySelectionRerollParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post lol champ select v1 session my selection reroll params
func (o *PostLolChampSelectV1SessionMySelectionRerollParams) WithContext(ctx context.Context) *PostLolChampSelectV1SessionMySelectionRerollParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post lol champ select v1 session my selection reroll params
func (o *PostLolChampSelectV1SessionMySelectionRerollParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post lol champ select v1 session my selection reroll params
func (o *PostLolChampSelectV1SessionMySelectionRerollParams) WithHTTPClient(client *http.Client) *PostLolChampSelectV1SessionMySelectionRerollParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post lol champ select v1 session my selection reroll params
func (o *PostLolChampSelectV1SessionMySelectionRerollParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostLolChampSelectV1SessionMySelectionRerollParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
