// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLolGameflowV1AckFailedToLaunchReader is a Reader for the PostLolGameflowV1AckFailedToLaunch structure.
type PostLolGameflowV1AckFailedToLaunchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLolGameflowV1AckFailedToLaunchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostLolGameflowV1AckFailedToLaunchNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLolGameflowV1AckFailedToLaunchNoContent creates a PostLolGameflowV1AckFailedToLaunchNoContent with default headers values
func NewPostLolGameflowV1AckFailedToLaunchNoContent() *PostLolGameflowV1AckFailedToLaunchNoContent {
	return &PostLolGameflowV1AckFailedToLaunchNoContent{}
}

/*PostLolGameflowV1AckFailedToLaunchNoContent handles this case with default header values.

No content
*/
type PostLolGameflowV1AckFailedToLaunchNoContent struct {
}

func (o *PostLolGameflowV1AckFailedToLaunchNoContent) Error() string {
	return fmt.Sprintf("[POST /lol-gameflow/v1/ack-failed-to-launch][%d] postLolGameflowV1AckFailedToLaunchNoContent ", 204)
}

func (o *PostLolGameflowV1AckFailedToLaunchNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
