// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLolClashV1VoiceDelayByDelaySecondsReader is a Reader for the PostLolClashV1VoiceDelayByDelaySeconds structure.
type PostLolClashV1VoiceDelayByDelaySecondsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLolClashV1VoiceDelayByDelaySecondsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostLolClashV1VoiceDelayByDelaySecondsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLolClashV1VoiceDelayByDelaySecondsOK creates a PostLolClashV1VoiceDelayByDelaySecondsOK with default headers values
func NewPostLolClashV1VoiceDelayByDelaySecondsOK() *PostLolClashV1VoiceDelayByDelaySecondsOK {
	return &PostLolClashV1VoiceDelayByDelaySecondsOK{}
}

/*PostLolClashV1VoiceDelayByDelaySecondsOK handles this case with default header values.

Successful response
*/
type PostLolClashV1VoiceDelayByDelaySecondsOK struct {
	Payload interface{}
}

func (o *PostLolClashV1VoiceDelayByDelaySecondsOK) Error() string {
	return fmt.Sprintf("[POST /lol-clash/v1/voice-delay/{delaySeconds}][%d] postLolClashV1VoiceDelayByDelaySecondsOK  %+v", 200, o.Payload)
}

func (o *PostLolClashV1VoiceDelayByDelaySecondsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PostLolClashV1VoiceDelayByDelaySecondsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
