// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// NewPostLolLoginV1SummonerCreatedParams creates a new PostLolLoginV1SummonerCreatedParams object
// with the default values initialized.
func NewPostLolLoginV1SummonerCreatedParams() *PostLolLoginV1SummonerCreatedParams {
	var ()
	return &PostLolLoginV1SummonerCreatedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLolLoginV1SummonerCreatedParamsWithTimeout creates a new PostLolLoginV1SummonerCreatedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLolLoginV1SummonerCreatedParamsWithTimeout(timeout time.Duration) *PostLolLoginV1SummonerCreatedParams {
	var ()
	return &PostLolLoginV1SummonerCreatedParams{

		timeout: timeout,
	}
}

// NewPostLolLoginV1SummonerCreatedParamsWithContext creates a new PostLolLoginV1SummonerCreatedParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLolLoginV1SummonerCreatedParamsWithContext(ctx context.Context) *PostLolLoginV1SummonerCreatedParams {
	var ()
	return &PostLolLoginV1SummonerCreatedParams{

		Context: ctx,
	}
}

// NewPostLolLoginV1SummonerCreatedParamsWithHTTPClient creates a new PostLolLoginV1SummonerCreatedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLolLoginV1SummonerCreatedParamsWithHTTPClient(client *http.Client) *PostLolLoginV1SummonerCreatedParams {
	var ()
	return &PostLolLoginV1SummonerCreatedParams{
		HTTPClient: client,
	}
}

/*PostLolLoginV1SummonerCreatedParams contains all the parameters to send to the API endpoint
for the post lol login v1 summoner created operation typically these are written to a http.Request
*/
type PostLolLoginV1SummonerCreatedParams struct {

	/*SummonerID*/
	SummonerID *models.LolLoginSummonerCreatedResource

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post lol login v1 summoner created params
func (o *PostLolLoginV1SummonerCreatedParams) WithTimeout(timeout time.Duration) *PostLolLoginV1SummonerCreatedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post lol login v1 summoner created params
func (o *PostLolLoginV1SummonerCreatedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post lol login v1 summoner created params
func (o *PostLolLoginV1SummonerCreatedParams) WithContext(ctx context.Context) *PostLolLoginV1SummonerCreatedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post lol login v1 summoner created params
func (o *PostLolLoginV1SummonerCreatedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post lol login v1 summoner created params
func (o *PostLolLoginV1SummonerCreatedParams) WithHTTPClient(client *http.Client) *PostLolLoginV1SummonerCreatedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post lol login v1 summoner created params
func (o *PostLolLoginV1SummonerCreatedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSummonerID adds the summonerID to the post lol login v1 summoner created params
func (o *PostLolLoginV1SummonerCreatedParams) WithSummonerID(summonerID *models.LolLoginSummonerCreatedResource) *PostLolLoginV1SummonerCreatedParams {
	o.SetSummonerID(summonerID)
	return o
}

// SetSummonerID adds the summonerId to the post lol login v1 summoner created params
func (o *PostLolLoginV1SummonerCreatedParams) SetSummonerID(summonerID *models.LolLoginSummonerCreatedResource) {
	o.SummonerID = summonerID
}

// WriteToRequest writes these params to a swagger request
func (o *PostLolLoginV1SummonerCreatedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SummonerID != nil {
		if err := r.SetBodyParam(o.SummonerID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
