// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostLolGameflowV1ExtraGameClientArgsParams creates a new PostLolGameflowV1ExtraGameClientArgsParams object
// with the default values initialized.
func NewPostLolGameflowV1ExtraGameClientArgsParams() *PostLolGameflowV1ExtraGameClientArgsParams {
	var ()
	return &PostLolGameflowV1ExtraGameClientArgsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLolGameflowV1ExtraGameClientArgsParamsWithTimeout creates a new PostLolGameflowV1ExtraGameClientArgsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLolGameflowV1ExtraGameClientArgsParamsWithTimeout(timeout time.Duration) *PostLolGameflowV1ExtraGameClientArgsParams {
	var ()
	return &PostLolGameflowV1ExtraGameClientArgsParams{

		timeout: timeout,
	}
}

// NewPostLolGameflowV1ExtraGameClientArgsParamsWithContext creates a new PostLolGameflowV1ExtraGameClientArgsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLolGameflowV1ExtraGameClientArgsParamsWithContext(ctx context.Context) *PostLolGameflowV1ExtraGameClientArgsParams {
	var ()
	return &PostLolGameflowV1ExtraGameClientArgsParams{

		Context: ctx,
	}
}

// NewPostLolGameflowV1ExtraGameClientArgsParamsWithHTTPClient creates a new PostLolGameflowV1ExtraGameClientArgsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLolGameflowV1ExtraGameClientArgsParamsWithHTTPClient(client *http.Client) *PostLolGameflowV1ExtraGameClientArgsParams {
	var ()
	return &PostLolGameflowV1ExtraGameClientArgsParams{
		HTTPClient: client,
	}
}

/*PostLolGameflowV1ExtraGameClientArgsParams contains all the parameters to send to the API endpoint
for the post lol gameflow v1 extra game client args operation typically these are written to a http.Request
*/
type PostLolGameflowV1ExtraGameClientArgsParams struct {

	/*ExtraGameClientArgs*/
	ExtraGameClientArgs []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post lol gameflow v1 extra game client args params
func (o *PostLolGameflowV1ExtraGameClientArgsParams) WithTimeout(timeout time.Duration) *PostLolGameflowV1ExtraGameClientArgsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post lol gameflow v1 extra game client args params
func (o *PostLolGameflowV1ExtraGameClientArgsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post lol gameflow v1 extra game client args params
func (o *PostLolGameflowV1ExtraGameClientArgsParams) WithContext(ctx context.Context) *PostLolGameflowV1ExtraGameClientArgsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post lol gameflow v1 extra game client args params
func (o *PostLolGameflowV1ExtraGameClientArgsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post lol gameflow v1 extra game client args params
func (o *PostLolGameflowV1ExtraGameClientArgsParams) WithHTTPClient(client *http.Client) *PostLolGameflowV1ExtraGameClientArgsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post lol gameflow v1 extra game client args params
func (o *PostLolGameflowV1ExtraGameClientArgsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExtraGameClientArgs adds the extraGameClientArgs to the post lol gameflow v1 extra game client args params
func (o *PostLolGameflowV1ExtraGameClientArgsParams) WithExtraGameClientArgs(extraGameClientArgs []string) *PostLolGameflowV1ExtraGameClientArgsParams {
	o.SetExtraGameClientArgs(extraGameClientArgs)
	return o
}

// SetExtraGameClientArgs adds the extraGameClientArgs to the post lol gameflow v1 extra game client args params
func (o *PostLolGameflowV1ExtraGameClientArgsParams) SetExtraGameClientArgs(extraGameClientArgs []string) {
	o.ExtraGameClientArgs = extraGameClientArgs
}

// WriteToRequest writes these params to a swagger request
func (o *PostLolGameflowV1ExtraGameClientArgsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ExtraGameClientArgs != nil {
		if err := r.SetBodyParam(o.ExtraGameClientArgs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
