// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// PostLolLoginV1SessionInvokeReader is a Reader for the PostLolLoginV1SessionInvoke structure.
type PostLolLoginV1SessionInvokeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLolLoginV1SessionInvokeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostLolLoginV1SessionInvokeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLolLoginV1SessionInvokeOK creates a PostLolLoginV1SessionInvokeOK with default headers values
func NewPostLolLoginV1SessionInvokeOK() *PostLolLoginV1SessionInvokeOK {
	return &PostLolLoginV1SessionInvokeOK{}
}

/*PostLolLoginV1SessionInvokeOK handles this case with default header values.

Successful response
*/
type PostLolLoginV1SessionInvokeOK struct {
	Payload *models.LolLoginLcdsResponse
}

func (o *PostLolLoginV1SessionInvokeOK) Error() string {
	return fmt.Sprintf("[POST /lol-login/v1/session/invoke][%d] postLolLoginV1SessionInvokeOK  %+v", 200, o.Payload)
}

func (o *PostLolLoginV1SessionInvokeOK) GetPayload() *models.LolLoginLcdsResponse {
	return o.Payload
}

func (o *PostLolLoginV1SessionInvokeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolLoginLcdsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
