// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLolLobbyV2LobbyMatchmakingSearchReader is a Reader for the PostLolLobbyV2LobbyMatchmakingSearch structure.
type PostLolLobbyV2LobbyMatchmakingSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLolLobbyV2LobbyMatchmakingSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostLolLobbyV2LobbyMatchmakingSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLolLobbyV2LobbyMatchmakingSearchOK creates a PostLolLobbyV2LobbyMatchmakingSearchOK with default headers values
func NewPostLolLobbyV2LobbyMatchmakingSearchOK() *PostLolLobbyV2LobbyMatchmakingSearchOK {
	return &PostLolLobbyV2LobbyMatchmakingSearchOK{}
}

/*PostLolLobbyV2LobbyMatchmakingSearchOK handles this case with default header values.

Successful response
*/
type PostLolLobbyV2LobbyMatchmakingSearchOK struct {
	Payload interface{}
}

func (o *PostLolLobbyV2LobbyMatchmakingSearchOK) Error() string {
	return fmt.Sprintf("[POST /lol-lobby/v2/lobby/matchmaking/search][%d] postLolLobbyV2LobbyMatchmakingSearchOK  %+v", 200, o.Payload)
}

func (o *PostLolLobbyV2LobbyMatchmakingSearchOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PostLolLobbyV2LobbyMatchmakingSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
