// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// PostLolLobbyV2EogInvitationsReader is a Reader for the PostLolLobbyV2EogInvitations structure.
type PostLolLobbyV2EogInvitationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLolLobbyV2EogInvitationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostLolLobbyV2EogInvitationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLolLobbyV2EogInvitationsOK creates a PostLolLobbyV2EogInvitationsOK with default headers values
func NewPostLolLobbyV2EogInvitationsOK() *PostLolLobbyV2EogInvitationsOK {
	return &PostLolLobbyV2EogInvitationsOK{}
}

/*PostLolLobbyV2EogInvitationsOK handles this case with default header values.

Successful response
*/
type PostLolLobbyV2EogInvitationsOK struct {
	Payload []*models.LolLobbyLobbyInvitationDto
}

func (o *PostLolLobbyV2EogInvitationsOK) Error() string {
	return fmt.Sprintf("[POST /lol-lobby/v2/eog-invitations][%d] postLolLobbyV2EogInvitationsOK  %+v", 200, o.Payload)
}

func (o *PostLolLobbyV2EogInvitationsOK) GetPayload() []*models.LolLobbyLobbyInvitationDto {
	return o.Payload
}

func (o *PostLolLobbyV2EogInvitationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
