// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLolLoginV1AccountStateReader is a Reader for the PostLolLoginV1AccountState structure.
type PostLolLoginV1AccountStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLolLoginV1AccountStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostLolLoginV1AccountStateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLolLoginV1AccountStateNoContent creates a PostLolLoginV1AccountStateNoContent with default headers values
func NewPostLolLoginV1AccountStateNoContent() *PostLolLoginV1AccountStateNoContent {
	return &PostLolLoginV1AccountStateNoContent{}
}

/*PostLolLoginV1AccountStateNoContent handles this case with default header values.

No content
*/
type PostLolLoginV1AccountStateNoContent struct {
}

func (o *PostLolLoginV1AccountStateNoContent) Error() string {
	return fmt.Sprintf("[POST /lol-login/v1/account-state][%d] postLolLoginV1AccountStateNoContent ", 204)
}

func (o *PostLolLoginV1AccountStateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
