// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// NewPostLolCareerStatsV1ChampionStatsPercentilesParams creates a new PostLolCareerStatsV1ChampionStatsPercentilesParams object
// with the default values initialized.
func NewPostLolCareerStatsV1ChampionStatsPercentilesParams() *PostLolCareerStatsV1ChampionStatsPercentilesParams {
	var ()
	return &PostLolCareerStatsV1ChampionStatsPercentilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLolCareerStatsV1ChampionStatsPercentilesParamsWithTimeout creates a new PostLolCareerStatsV1ChampionStatsPercentilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLolCareerStatsV1ChampionStatsPercentilesParamsWithTimeout(timeout time.Duration) *PostLolCareerStatsV1ChampionStatsPercentilesParams {
	var ()
	return &PostLolCareerStatsV1ChampionStatsPercentilesParams{

		timeout: timeout,
	}
}

// NewPostLolCareerStatsV1ChampionStatsPercentilesParamsWithContext creates a new PostLolCareerStatsV1ChampionStatsPercentilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLolCareerStatsV1ChampionStatsPercentilesParamsWithContext(ctx context.Context) *PostLolCareerStatsV1ChampionStatsPercentilesParams {
	var ()
	return &PostLolCareerStatsV1ChampionStatsPercentilesParams{

		Context: ctx,
	}
}

// NewPostLolCareerStatsV1ChampionStatsPercentilesParamsWithHTTPClient creates a new PostLolCareerStatsV1ChampionStatsPercentilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLolCareerStatsV1ChampionStatsPercentilesParamsWithHTTPClient(client *http.Client) *PostLolCareerStatsV1ChampionStatsPercentilesParams {
	var ()
	return &PostLolCareerStatsV1ChampionStatsPercentilesParams{
		HTTPClient: client,
	}
}

/*PostLolCareerStatsV1ChampionStatsPercentilesParams contains all the parameters to send to the API endpoint
for the post lol career stats v1 champion stats percentiles operation typically these are written to a http.Request
*/
type PostLolCareerStatsV1ChampionStatsPercentilesParams struct {

	/*Body*/
	Body []*models.LolCareerStatsStatsQueryRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post lol career stats v1 champion stats percentiles params
func (o *PostLolCareerStatsV1ChampionStatsPercentilesParams) WithTimeout(timeout time.Duration) *PostLolCareerStatsV1ChampionStatsPercentilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post lol career stats v1 champion stats percentiles params
func (o *PostLolCareerStatsV1ChampionStatsPercentilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post lol career stats v1 champion stats percentiles params
func (o *PostLolCareerStatsV1ChampionStatsPercentilesParams) WithContext(ctx context.Context) *PostLolCareerStatsV1ChampionStatsPercentilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post lol career stats v1 champion stats percentiles params
func (o *PostLolCareerStatsV1ChampionStatsPercentilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post lol career stats v1 champion stats percentiles params
func (o *PostLolCareerStatsV1ChampionStatsPercentilesParams) WithHTTPClient(client *http.Client) *PostLolCareerStatsV1ChampionStatsPercentilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post lol career stats v1 champion stats percentiles params
func (o *PostLolCareerStatsV1ChampionStatsPercentilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post lol career stats v1 champion stats percentiles params
func (o *PostLolCareerStatsV1ChampionStatsPercentilesParams) WithBody(body []*models.LolCareerStatsStatsQueryRequest) *PostLolCareerStatsV1ChampionStatsPercentilesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post lol career stats v1 champion stats percentiles params
func (o *PostLolCareerStatsV1ChampionStatsPercentilesParams) SetBody(body []*models.LolCareerStatsStatsQueryRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostLolCareerStatsV1ChampionStatsPercentilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
