// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLolClashV1GameEndAcknowledgeReader is a Reader for the PostLolClashV1GameEndAcknowledge structure.
type PostLolClashV1GameEndAcknowledgeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLolClashV1GameEndAcknowledgeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostLolClashV1GameEndAcknowledgeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLolClashV1GameEndAcknowledgeOK creates a PostLolClashV1GameEndAcknowledgeOK with default headers values
func NewPostLolClashV1GameEndAcknowledgeOK() *PostLolClashV1GameEndAcknowledgeOK {
	return &PostLolClashV1GameEndAcknowledgeOK{}
}

/*PostLolClashV1GameEndAcknowledgeOK handles this case with default header values.

Successful response
*/
type PostLolClashV1GameEndAcknowledgeOK struct {
	Payload interface{}
}

func (o *PostLolClashV1GameEndAcknowledgeOK) Error() string {
	return fmt.Sprintf("[POST /lol-clash/v1/game-end/acknowledge][%d] postLolClashV1GameEndAcknowledgeOK  %+v", 200, o.Payload)
}

func (o *PostLolClashV1GameEndAcknowledgeOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PostLolClashV1GameEndAcknowledgeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
