// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/paralin/go-rift-api/models"
)

// PutLolLoadoutsV4LoadoutsByIDReader is a Reader for the PutLolLoadoutsV4LoadoutsByID structure.
type PutLolLoadoutsV4LoadoutsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutLolLoadoutsV4LoadoutsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutLolLoadoutsV4LoadoutsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutLolLoadoutsV4LoadoutsByIDOK creates a PutLolLoadoutsV4LoadoutsByIDOK with default headers values
func NewPutLolLoadoutsV4LoadoutsByIDOK() *PutLolLoadoutsV4LoadoutsByIDOK {
	return &PutLolLoadoutsV4LoadoutsByIDOK{}
}

/*PutLolLoadoutsV4LoadoutsByIDOK handles this case with default header values.

Successful response
*/
type PutLolLoadoutsV4LoadoutsByIDOK struct {
	Payload *models.LolLoadoutsScopedLoadout
}

func (o *PutLolLoadoutsV4LoadoutsByIDOK) Error() string {
	return fmt.Sprintf("[PUT /lol-loadouts/v4/loadouts/{id}][%d] putLolLoadoutsV4LoadoutsByIdOK  %+v", 200, o.Payload)
}

func (o *PutLolLoadoutsV4LoadoutsByIDOK) GetPayload() *models.LolLoadoutsScopedLoadout {
	return o.Payload
}

func (o *PutLolLoadoutsV4LoadoutsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LolLoadoutsScopedLoadout)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
