// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutVoiceChatV2DevicesCapturePromptForPermissionReader is a Reader for the PutVoiceChatV2DevicesCapturePromptForPermission structure.
type PutVoiceChatV2DevicesCapturePromptForPermissionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutVoiceChatV2DevicesCapturePromptForPermissionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPutVoiceChatV2DevicesCapturePromptForPermissionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutVoiceChatV2DevicesCapturePromptForPermissionNoContent creates a PutVoiceChatV2DevicesCapturePromptForPermissionNoContent with default headers values
func NewPutVoiceChatV2DevicesCapturePromptForPermissionNoContent() *PutVoiceChatV2DevicesCapturePromptForPermissionNoContent {
	return &PutVoiceChatV2DevicesCapturePromptForPermissionNoContent{}
}

/*PutVoiceChatV2DevicesCapturePromptForPermissionNoContent handles this case with default header values.

No content
*/
type PutVoiceChatV2DevicesCapturePromptForPermissionNoContent struct {
}

func (o *PutVoiceChatV2DevicesCapturePromptForPermissionNoContent) Error() string {
	return fmt.Sprintf("[PUT /voice-chat/v2/devices/capture/prompt-for-permission][%d] putVoiceChatV2DevicesCapturePromptForPermissionNoContent ", 204)
}

func (o *PutVoiceChatV2DevicesCapturePromptForPermissionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
