// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutLolMissionsV1PlayerReader is a Reader for the PutLolMissionsV1Player structure.
type PutLolMissionsV1PlayerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutLolMissionsV1PlayerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPutLolMissionsV1PlayerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutLolMissionsV1PlayerNoContent creates a PutLolMissionsV1PlayerNoContent with default headers values
func NewPutLolMissionsV1PlayerNoContent() *PutLolMissionsV1PlayerNoContent {
	return &PutLolMissionsV1PlayerNoContent{}
}

/*PutLolMissionsV1PlayerNoContent handles this case with default header values.

No content
*/
type PutLolMissionsV1PlayerNoContent struct {
}

func (o *PutLolMissionsV1PlayerNoContent) Error() string {
	return fmt.Sprintf("[PUT /lol-missions/v1/player][%d] putLolMissionsV1PlayerNoContent ", 204)
}

func (o *PutLolMissionsV1PlayerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
