// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClientConfigDepInjectorEntitlementsUpdate client config dep injector entitlements update
// swagger:model ClientConfigDepInjectorEntitlementsUpdate
type ClientConfigDepInjectorEntitlementsUpdate struct {

	// entitlements token resource
	EntitlementsTokenResource *ClientConfigDepInjectorEntitlements `json:"EntitlementsTokenResource,omitempty"`

	// entitlements update type
	EntitlementsUpdateType ClientConfigDepInjectorEntitlementsUpdateType `json:"EntitlementsUpdateType,omitempty"`
}

// Validate validates this client config dep injector entitlements update
func (m *ClientConfigDepInjectorEntitlementsUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEntitlementsTokenResource(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntitlementsUpdateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClientConfigDepInjectorEntitlementsUpdate) validateEntitlementsTokenResource(formats strfmt.Registry) error {

	if swag.IsZero(m.EntitlementsTokenResource) { // not required
		return nil
	}

	if m.EntitlementsTokenResource != nil {
		if err := m.EntitlementsTokenResource.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("EntitlementsTokenResource")
			}
			return err
		}
	}

	return nil
}

func (m *ClientConfigDepInjectorEntitlementsUpdate) validateEntitlementsUpdateType(formats strfmt.Registry) error {

	if swag.IsZero(m.EntitlementsUpdateType) { // not required
		return nil
	}

	if err := m.EntitlementsUpdateType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("EntitlementsUpdateType")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClientConfigDepInjectorEntitlementsUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClientConfigDepInjectorEntitlementsUpdate) UnmarshalBinary(b []byte) error {
	var res ClientConfigDepInjectorEntitlementsUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
