// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LcdsStartChampSelectDto lcds start champ select dto
// swagger:model LcdsStartChampSelectDto
type LcdsStartChampSelectDto struct {

	// invalid players
	InvalidPlayers []*LcdsFailedJoinPlayer `json:"invalidPlayers"`
}

// Validate validates this lcds start champ select dto
func (m *LcdsStartChampSelectDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInvalidPlayers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LcdsStartChampSelectDto) validateInvalidPlayers(formats strfmt.Registry) error {

	if swag.IsZero(m.InvalidPlayers) { // not required
		return nil
	}

	for i := 0; i < len(m.InvalidPlayers); i++ {
		if swag.IsZero(m.InvalidPlayers[i]) { // not required
			continue
		}

		if m.InvalidPlayers[i] != nil {
			if err := m.InvalidPlayers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("invalidPlayers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LcdsStartChampSelectDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LcdsStartChampSelectDto) UnmarshalBinary(b []byte) error {
	var res LcdsStartChampSelectDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
