// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolLicenseAgreementLicenseAgreement lol license agreement license agreement
// swagger:model LolLicenseAgreementLicenseAgreement
type LolLicenseAgreementLicenseAgreement struct {

	// id
	ID string `json:"id,omitempty"`

	// license type
	LicenseType LolLicenseAgreementLicenseAgreementType `json:"licenseType,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this lol license agreement license agreement
func (m *LolLicenseAgreementLicenseAgreement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLicenseType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolLicenseAgreementLicenseAgreement) validateLicenseType(formats strfmt.Registry) error {

	if swag.IsZero(m.LicenseType) { // not required
		return nil
	}

	if err := m.LicenseType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("licenseType")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolLicenseAgreementLicenseAgreement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolLicenseAgreementLicenseAgreement) UnmarshalBinary(b []byte) error {
	var res LolLicenseAgreementLicenseAgreement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
