// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolQueueEligibilityQueue lol queue eligibility queue
// swagger:model LolQueueEligibilityQueue
type LolQueueEligibilityQueue struct {

	// allowable premade sizes
	AllowablePremadeSizes []int32 `json:"allowablePremadeSizes"`

	// are free champions allowed
	AreFreeChampionsAllowed bool `json:"areFreeChampionsAllowed,omitempty"`

	// champions required to play
	ChampionsRequiredToPlay int32 `json:"championsRequiredToPlay,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// is ranked
	IsRanked bool `json:"isRanked,omitempty"`

	// max level
	MaxLevel int32 `json:"maxLevel,omitempty"`

	// maximum participant list size
	MaximumParticipantListSize int32 `json:"maximumParticipantListSize,omitempty"`

	// min level
	MinLevel int32 `json:"minLevel,omitempty"`

	// num players per team
	NumPlayersPerTeam int32 `json:"numPlayersPerTeam,omitempty"`

	// queue availability
	QueueAvailability LolQueueEligibilityQueueAvailability `json:"queueAvailability,omitempty"`

	// show position selector
	ShowPositionSelector bool `json:"showPositionSelector,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this lol queue eligibility queue
func (m *LolQueueEligibilityQueue) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQueueAvailability(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolQueueEligibilityQueue) validateQueueAvailability(formats strfmt.Registry) error {

	if swag.IsZero(m.QueueAvailability) { // not required
		return nil
	}

	if err := m.QueueAvailability.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("queueAvailability")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolQueueEligibilityQueue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolQueueEligibilityQueue) UnmarshalBinary(b []byte) error {
	var res LolQueueEligibilityQueue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
