// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolClashGameflowPartiesRegistrationStatus lol clash gameflow parties registration status
// swagger:model LolClashGameflowPartiesRegistrationStatus
type LolClashGameflowPartiesRegistrationStatus struct {

	// complete
	Complete bool `json:"complete,omitempty"`

	// error codes
	ErrorCodes []string `json:"errorCodes"`
}

// Validate validates this lol clash gameflow parties registration status
func (m *LolClashGameflowPartiesRegistrationStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolClashGameflowPartiesRegistrationStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolClashGameflowPartiesRegistrationStatus) UnmarshalBinary(b []byte) error {
	var res LolClashGameflowPartiesRegistrationStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
