// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolChampSelectCollectionsChampionMinimal lol champ select collections champion minimal
// swagger:model LolChampSelectCollectionsChampionMinimal
type LolChampSelectCollectionsChampionMinimal struct {

	// ban vo path
	BanVoPath string `json:"banVoPath,omitempty"`

	// choose vo path
	ChooseVoPath string `json:"chooseVoPath,omitempty"`

	// disabled queues
	DisabledQueues []string `json:"disabledQueues"`

	// free to play
	FreeToPlay bool `json:"freeToPlay,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// ownership
	Ownership *LolChampSelectCollectionsOwnership `json:"ownership,omitempty"`

	// roles
	Roles []string `json:"roles"`

	// square portrait path
	SquarePortraitPath string `json:"squarePortraitPath,omitempty"`

	// stinger sfx path
	StingerSfxPath string `json:"stingerSfxPath,omitempty"`
}

// Validate validates this lol champ select collections champion minimal
func (m *LolChampSelectCollectionsChampionMinimal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOwnership(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolChampSelectCollectionsChampionMinimal) validateOwnership(formats strfmt.Registry) error {

	if swag.IsZero(m.Ownership) { // not required
		return nil
	}

	if m.Ownership != nil {
		if err := m.Ownership.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ownership")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolChampSelectCollectionsChampionMinimal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolChampSelectCollectionsChampionMinimal) UnmarshalBinary(b []byte) error {
	var res LolChampSelectCollectionsChampionMinimal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
