// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolPremadeVoiceFirstExperience lol premade voice first experience
// swagger:model LolPremadeVoiceFirstExperience
type LolPremadeVoiceFirstExperience struct {

	// show first experience in game
	ShowFirstExperienceInGame bool `json:"showFirstExperienceInGame,omitempty"`

	// show first experience in l c u
	ShowFirstExperienceInLCU bool `json:"showFirstExperienceInLCU,omitempty"`
}

// Validate validates this lol premade voice first experience
func (m *LolPremadeVoiceFirstExperience) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolPremadeVoiceFirstExperience) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolPremadeVoiceFirstExperience) UnmarshalBinary(b []byte) error {
	var res LolPremadeVoiceFirstExperience
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
