// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolRankedEosNotificationsConfigEntry lol ranked eos notifications config entry
// swagger:model LolRankedEosNotificationsConfigEntry
type LolRankedEosNotificationsConfigEntry struct {

	// name
	Name string `json:"name,omitempty"`

	// offset time1
	OffsetTime1 int64 `json:"offsetTime1,omitempty"`

	// offset time2
	OffsetTime2 int64 `json:"offsetTime2,omitempty"`

	// offset time3
	OffsetTime3 int64 `json:"offsetTime3,omitempty"`

	// season end time
	SeasonEndTime int64 `json:"seasonEndTime,omitempty"`
}

// Validate validates this lol ranked eos notifications config entry
func (m *LolRankedEosNotificationsConfigEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolRankedEosNotificationsConfigEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolRankedEosNotificationsConfigEntry) UnmarshalBinary(b []byte) error {
	var res LolRankedEosNotificationsConfigEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
