// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolWorldsTokenCardCollectionsSummonerIcons lol worlds token card collections summoner icons
// swagger:model LolWorldsTokenCardCollectionsSummonerIcons
type LolWorldsTokenCardCollectionsSummonerIcons struct {

	// icons
	Icons []int32 `json:"icons"`
}

// Validate validates this lol worlds token card collections summoner icons
func (m *LolWorldsTokenCardCollectionsSummonerIcons) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolWorldsTokenCardCollectionsSummonerIcons) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolWorldsTokenCardCollectionsSummonerIcons) UnmarshalBinary(b []byte) error {
	var res LolWorldsTokenCardCollectionsSummonerIcons
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
