// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolPftGameClientEndOfGameStats lol pft game client end of game stats
// swagger:model LolPftGameClientEndOfGameStats
type LolPftGameClientEndOfGameStats struct {

	// game Id
	GameID int64 `json:"gameId,omitempty"`

	// game mode
	GameMode string `json:"gameMode,omitempty"`

	// is ranked
	IsRanked bool `json:"isRanked,omitempty"`

	// queue Id
	QueueID int32 `json:"queueId,omitempty"`

	// stats block
	StatsBlock interface{} `json:"statsBlock,omitempty"`
}

// Validate validates this lol pft game client end of game stats
func (m *LolPftGameClientEndOfGameStats) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolPftGameClientEndOfGameStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolPftGameClientEndOfGameStats) UnmarshalBinary(b []byte) error {
	var res LolPftGameClientEndOfGameStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
