// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolMissionsTftBattlepass lol missions tft battlepass
// swagger:model LolMissionsTftBattlepass
type LolMissionsTftBattlepass struct {

	// milestones
	Milestones []*LolMissionsTftBattlepassMilestone `json:"milestones"`

	// total points earned
	TotalPointsEarned int32 `json:"totalPointsEarned,omitempty"`
}

// Validate validates this lol missions tft battlepass
func (m *LolMissionsTftBattlepass) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMilestones(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolMissionsTftBattlepass) validateMilestones(formats strfmt.Registry) error {

	if swag.IsZero(m.Milestones) { // not required
		return nil
	}

	for i := 0; i < len(m.Milestones); i++ {
		if swag.IsZero(m.Milestones[i]) { // not required
			continue
		}

		if m.Milestones[i] != nil {
			if err := m.Milestones[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("milestones" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolMissionsTftBattlepass) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolMissionsTftBattlepass) UnmarshalBinary(b []byte) error {
	var res LolMissionsTftBattlepass
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
