// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolMissionsCollectionsSummoner lol missions collections summoner
// swagger:model LolMissionsCollectionsSummoner
type LolMissionsCollectionsSummoner struct {

	// summoner level
	SummonerLevel int32 `json:"summonerLevel,omitempty"`
}

// Validate validates this lol missions collections summoner
func (m *LolMissionsCollectionsSummoner) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolMissionsCollectionsSummoner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolMissionsCollectionsSummoner) UnmarshalBinary(b []byte) error {
	var res LolMissionsCollectionsSummoner
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
