// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolTencentQtTencentQTNotification lol tencent qt tencent q t notification
// swagger:model LolTencentQtTencentQTNotification
type LolTencentQtTencentQTNotification struct {

	// data
	Data interface{} `json:"data,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// updated by
	UpdatedBy string `json:"updatedBy,omitempty"`
}

// Validate validates this lol tencent qt tencent q t notification
func (m *LolTencentQtTencentQTNotification) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolTencentQtTencentQTNotification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolTencentQtTencentQTNotification) UnmarshalBinary(b []byte) error {
	var res LolTencentQtTencentQTNotification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
