// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolPersonalizedOffersOfferIds lol personalized offers offer ids
// swagger:model LolPersonalizedOffersOfferIds
type LolPersonalizedOffersOfferIds struct {

	// offers
	Offers []*LolPersonalizedOffersOfferID `json:"offers"`
}

// Validate validates this lol personalized offers offer ids
func (m *LolPersonalizedOffersOfferIds) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOffers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolPersonalizedOffersOfferIds) validateOffers(formats strfmt.Registry) error {

	if swag.IsZero(m.Offers) { // not required
		return nil
	}

	for i := 0; i < len(m.Offers); i++ {
		if swag.IsZero(m.Offers[i]) { // not required
			continue
		}

		if m.Offers[i] != nil {
			if err := m.Offers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("offers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolPersonalizedOffersOfferIds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolPersonalizedOffersOfferIds) UnmarshalBinary(b []byte) error {
	var res LolPersonalizedOffersOfferIds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
