// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolChatGroupResource lol chat group resource
// swagger:model LolChatGroupResource
type LolChatGroupResource struct {

	// collapsed
	Collapsed bool `json:"collapsed,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// is localized
	IsLocalized bool `json:"isLocalized,omitempty"`

	// is meta group
	IsMetaGroup bool `json:"isMetaGroup,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// priority
	Priority int32 `json:"priority,omitempty"`
}

// Validate validates this lol chat group resource
func (m *LolChatGroupResource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolChatGroupResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolChatGroupResource) UnmarshalBinary(b []byte) error {
	var res LolChatGroupResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
