// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolMatchHistoryMatchHistoryTeamBan lol match history match history team ban
// swagger:model LolMatchHistoryMatchHistoryTeamBan
type LolMatchHistoryMatchHistoryTeamBan struct {

	// champion Id
	ChampionID int32 `json:"championId,omitempty"`

	// pick turn
	PickTurn int64 `json:"pickTurn,omitempty"`
}

// Validate validates this lol match history match history team ban
func (m *LolMatchHistoryMatchHistoryTeamBan) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolMatchHistoryMatchHistoryTeamBan) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolMatchHistoryMatchHistoryTeamBan) UnmarshalBinary(b []byte) error {
	var res LolMatchHistoryMatchHistoryTeamBan
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
