// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolSuggestedPlayersSuggestedPlayersLobbyStatus lol suggested players suggested players lobby status
// swagger:model LolSuggestedPlayersSuggestedPlayersLobbyStatus
type LolSuggestedPlayersSuggestedPlayersLobbyStatus struct {

	// invited summoner ids
	InvitedSummonerIds []int64 `json:"invitedSummonerIds"`

	// member summoner ids
	MemberSummonerIds []int64 `json:"memberSummonerIds"`

	// queue Id
	QueueID int32 `json:"queueId,omitempty"`
}

// Validate validates this lol suggested players suggested players lobby status
func (m *LolSuggestedPlayersSuggestedPlayersLobbyStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolSuggestedPlayersSuggestedPlayersLobbyStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolSuggestedPlayersSuggestedPlayersLobbyStatus) UnmarshalBinary(b []byte) error {
	var res LolSuggestedPlayersSuggestedPlayersLobbyStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
