// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolStoreGiftingFriend lol store gifting friend
// swagger:model LolStoreGiftingFriend
type LolStoreGiftingFriend struct {

	// friends since
	FriendsSince string `json:"friendsSince,omitempty"`

	// nick
	Nick string `json:"nick,omitempty"`

	// old friends
	OldFriends bool `json:"oldFriends,omitempty"`

	// summoner Id
	SummonerID int64 `json:"summonerId,omitempty"`
}

// Validate validates this lol store gifting friend
func (m *LolStoreGiftingFriend) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolStoreGiftingFriend) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolStoreGiftingFriend) UnmarshalBinary(b []byte) error {
	var res LolStoreGiftingFriend
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
