// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolChatMessage lol chat message
// swagger:model LolChatMessage
type LolChatMessage struct {

	// body
	Body string `json:"body,omitempty"`

	// cid
	Cid string `json:"cid,omitempty"`

	// game name
	GameName string `json:"game_name,omitempty"`

	// game tag
	GameTag string `json:"game_tag,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// mid
	Mid string `json:"mid,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pid
	Pid string `json:"pid,omitempty"`

	// read
	Read bool `json:"read,omitempty"`

	// time
	Time string `json:"time,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this lol chat message
func (m *LolChatMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolChatMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolChatMessage) UnmarshalBinary(b []byte) error {
	var res LolChatMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
