// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolGameflowInstallPaths lol gameflow install paths
// swagger:model LolGameflowInstallPaths
type LolGameflowInstallPaths struct {

	// game executable path
	GameExecutablePath string `json:"gameExecutablePath,omitempty"`

	// game install root
	GameInstallRoot string `json:"gameInstallRoot,omitempty"`
}

// Validate validates this lol gameflow install paths
func (m *LolGameflowInstallPaths) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolGameflowInstallPaths) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolGameflowInstallPaths) UnmarshalBinary(b []byte) error {
	var res LolGameflowInstallPaths
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
