// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolChatActiveConversationResource lol chat active conversation resource
// swagger:model LolChatActiveConversationResource
type LolChatActiveConversationResource struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this lol chat active conversation resource
func (m *LolChatActiveConversationResource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolChatActiveConversationResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolChatActiveConversationResource) UnmarshalBinary(b []byte) error {
	var res LolChatActiveConversationResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
