// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolPlayerBehaviorPlayerBehaviorLoginError lol player behavior player behavior login error
// swagger:model LolPlayerBehaviorPlayerBehavior_LoginError
type LolPlayerBehaviorPlayerBehaviorLoginError struct {

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// message Id
	MessageID string `json:"messageId,omitempty"`
}

// Validate validates this lol player behavior player behavior login error
func (m *LolPlayerBehaviorPlayerBehaviorLoginError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolPlayerBehaviorPlayerBehaviorLoginError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolPlayerBehaviorPlayerBehaviorLoginError) UnmarshalBinary(b []byte) error {
	var res LolPlayerBehaviorPlayerBehaviorLoginError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
