// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolClashPendingRosterNotification lol clash pending roster notification
// swagger:model LolClashPendingRosterNotification
type LolClashPendingRosterNotification struct {

	// notify reason
	NotifyReason LolClashNotifyReason `json:"notifyReason,omitempty"`

	// pending roster
	PendingRoster *PendingRosterDTO `json:"pendingRoster,omitempty"`

	// source player Id
	SourcePlayerID int64 `json:"sourcePlayerId,omitempty"`

	// target player Id
	TargetPlayerID int64 `json:"targetPlayerId,omitempty"`
}

// Validate validates this lol clash pending roster notification
func (m *LolClashPendingRosterNotification) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNotifyReason(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePendingRoster(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolClashPendingRosterNotification) validateNotifyReason(formats strfmt.Registry) error {

	if swag.IsZero(m.NotifyReason) { // not required
		return nil
	}

	if err := m.NotifyReason.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("notifyReason")
		}
		return err
	}

	return nil
}

func (m *LolClashPendingRosterNotification) validatePendingRoster(formats strfmt.Registry) error {

	if swag.IsZero(m.PendingRoster) { // not required
		return nil
	}

	if m.PendingRoster != nil {
		if err := m.PendingRoster.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pendingRoster")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolClashPendingRosterNotification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolClashPendingRosterNotification) UnmarshalBinary(b []byte) error {
	var res LolClashPendingRosterNotification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
