// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolPerksInventoryRunePageCount lol perks inventory rune page count
// swagger:model LolPerksInventoryRunePageCount
type LolPerksInventoryRunePageCount struct {

	// quantity
	Quantity int32 `json:"quantity,omitempty"`
}

// Validate validates this lol perks inventory rune page count
func (m *LolPerksInventoryRunePageCount) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolPerksInventoryRunePageCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolPerksInventoryRunePageCount) UnmarshalBinary(b []byte) error {
	var res LolPerksInventoryRunePageCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
