// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolPurchaseWidgetChampionSkinEmblemPosition lol purchase widget champion skin emblem position
// swagger:model LolPurchaseWidgetChampionSkinEmblemPosition
type LolPurchaseWidgetChampionSkinEmblemPosition struct {

	// horizontal
	Horizontal string `json:"horizontal,omitempty"`

	// vertical
	Vertical string `json:"vertical,omitempty"`
}

// Validate validates this lol purchase widget champion skin emblem position
func (m *LolPurchaseWidgetChampionSkinEmblemPosition) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolPurchaseWidgetChampionSkinEmblemPosition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolPurchaseWidgetChampionSkinEmblemPosition) UnmarshalBinary(b []byte) error {
	var res LolPurchaseWidgetChampionSkinEmblemPosition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
