// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolRegaliaRegaliaPlatformConfig lol regalia regalia platform config
// swagger:model LolRegaliaRegaliaPlatformConfig
type LolRegaliaRegaliaPlatformConfig struct {

	// hovercard enabled
	HovercardEnabled bool `json:"HovercardEnabled,omitempty"`

	// selections enabled
	SelectionsEnabled bool `json:"SelectionsEnabled,omitempty"`
}

// Validate validates this lol regalia regalia platform config
func (m *LolRegaliaRegaliaPlatformConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolRegaliaRegaliaPlatformConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolRegaliaRegaliaPlatformConfig) UnmarshalBinary(b []byte) error {
	var res LolRegaliaRegaliaPlatformConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
