// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolChampSelectChampionSelection lol champ select champion selection
// swagger:model LolChampSelectChampionSelection
type LolChampSelectChampionSelection struct {

	// ban intented
	BanIntented bool `json:"banIntented,omitempty"`

	// ban intented by me
	BanIntentedByMe bool `json:"banIntentedByMe,omitempty"`

	// is banned
	IsBanned bool `json:"isBanned,omitempty"`

	// pick intented
	PickIntented bool `json:"pickIntented,omitempty"`

	// pick intented by me
	PickIntentedByMe bool `json:"pickIntentedByMe,omitempty"`

	// pick intented position
	PickIntentedPosition string `json:"pickIntentedPosition,omitempty"`

	// picked by other or banned
	PickedByOtherOrBanned bool `json:"pickedByOtherOrBanned,omitempty"`

	// selected by me
	SelectedByMe bool `json:"selectedByMe,omitempty"`
}

// Validate validates this lol champ select champion selection
func (m *LolChampSelectChampionSelection) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolChampSelectChampionSelection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolChampSelectChampionSelection) UnmarshalBinary(b []byte) error {
	var res LolChampSelectChampionSelection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
