// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolClubsPublicClubPreferences lol clubs public club preferences
// swagger:model LolClubsPublicClubPreferences
type LolClubsPublicClubPreferences struct {

	// share club affiliation
	ShareClubAffiliation bool `json:"shareClubAffiliation,omitempty"`
}

// Validate validates this lol clubs public club preferences
func (m *LolClubsPublicClubPreferences) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolClubsPublicClubPreferences) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolClubsPublicClubPreferences) UnmarshalBinary(b []byte) error {
	var res LolClubsPublicClubPreferences
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
