// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolLootLootTableGdsResource lol loot loot table gds resource
// swagger:model LolLootLootTableGdsResource
type LolLootLootTableGdsResource struct {

	// description
	Description string `json:"description,omitempty"`

	// description long
	DescriptionLong string `json:"descriptionLong,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// image
	Image string `json:"image,omitempty"`
}

// Validate validates this lol loot loot table gds resource
func (m *LolLootLootTableGdsResource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolLootLootTableGdsResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolLootLootTableGdsResource) UnmarshalBinary(b []byte) error {
	var res LolLootLootTableGdsResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
