// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolPlayerBehaviorReformCardChatLogs lol player behavior reform card chat logs
// swagger:model LolPlayerBehaviorReformCardChatLogs
type LolPlayerBehaviorReformCardChatLogs struct {

	// in game chat logs
	InGameChatLogs []string `json:"inGameChatLogs"`

	// post game chat logs
	PostGameChatLogs []string `json:"postGameChatLogs"`

	// pre game chat logs
	PreGameChatLogs []string `json:"preGameChatLogs"`
}

// Validate validates this lol player behavior reform card chat logs
func (m *LolPlayerBehaviorReformCardChatLogs) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolPlayerBehaviorReformCardChatLogs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolPlayerBehaviorReformCardChatLogs) UnmarshalBinary(b []byte) error {
	var res LolPlayerBehaviorReformCardChatLogs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
