// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolClashClubsSummoner lol clash clubs summoner
// swagger:model LolClashClubsSummoner
type LolClashClubsSummoner struct {

	// display name
	DisplayName string `json:"displayName,omitempty"`

	// profile icon Id
	ProfileIconID int32 `json:"profileIconId,omitempty"`

	// summoner Id
	SummonerID int64 `json:"summonerId,omitempty"`

	// summoner level
	SummonerLevel int32 `json:"summonerLevel,omitempty"`
}

// Validate validates this lol clash clubs summoner
func (m *LolClashClubsSummoner) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolClashClubsSummoner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolClashClubsSummoner) UnmarshalBinary(b []byte) error {
	var res LolClashClubsSummoner
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
