// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolCatalogGameDataStatstone lol catalog game data statstone
// swagger:model LolCatalogGameDataStatstone
type LolCatalogGameDataStatstone struct {

	// category
	Category string `json:"category,omitempty"`

	// content Id
	ContentID string `json:"contentId,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// icon full
	IconFull string `json:"iconFull,omitempty"`

	// is duration
	IsDuration bool `json:"isDuration,omitempty"`

	// is epic
	IsEpic bool `json:"isEpic,omitempty"`

	// is retired
	IsRetired bool `json:"isRetired,omitempty"`

	// item Id
	ItemID int32 `json:"itemId,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this lol catalog game data statstone
func (m *LolCatalogGameDataStatstone) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolCatalogGameDataStatstone) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolCatalogGameDataStatstone) UnmarshalBinary(b []byte) error {
	var res LolCatalogGameDataStatstone
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
