// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolClubsPlayerMembershipPreferencesDto lol clubs player membership preferences dto
// swagger:model LolClubsPlayerMembershipPreferencesDto
type LolClubsPlayerMembershipPreferencesDto struct {

	// primary active club key
	PrimaryActiveClubKey string `json:"primaryActiveClubKey,omitempty"`

	// share club affiliation
	ShareClubAffiliation bool `json:"shareClubAffiliation,omitempty"`
}

// Validate validates this lol clubs player membership preferences dto
func (m *LolClubsPlayerMembershipPreferencesDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolClubsPlayerMembershipPreferencesDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolClubsPlayerMembershipPreferencesDto) UnmarshalBinary(b []byte) error {
	var res LolClubsPlayerMembershipPreferencesDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
