// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// LolClashClashVisibility lol clash clash visibility
// swagger:model LolClashClashVisibility
type LolClashClashVisibility string

const (

	// LolClashClashVisibilityHidden captures enum value "Hidden"
	LolClashClashVisibilityHidden LolClashClashVisibility = "Hidden"

	// LolClashClashVisibilityDarkVisible captures enum value "DarkVisible"
	LolClashClashVisibilityDarkVisible LolClashClashVisibility = "DarkVisible"

	// LolClashClashVisibilityVisible captures enum value "Visible"
	LolClashClashVisibilityVisible LolClashClashVisibility = "Visible"
)

// for schema
var lolClashClashVisibilityEnum []interface{}

func init() {
	var res []LolClashClashVisibility
	if err := json.Unmarshal([]byte(`["Hidden","DarkVisible","Visible"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		lolClashClashVisibilityEnum = append(lolClashClashVisibilityEnum, v)
	}
}

func (m LolClashClashVisibility) validateLolClashClashVisibilityEnum(path, location string, value LolClashClashVisibility) error {
	if err := validate.Enum(path, location, value, lolClashClashVisibilityEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this lol clash clash visibility
func (m LolClashClashVisibility) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateLolClashClashVisibilityEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
