// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolChatBlockedList lol chat blocked list
// swagger:model LolChatBlockedList
type LolChatBlockedList struct {

	// blocked
	Blocked []*LolChatBlocked `json:"blocked"`
}

// Validate validates this lol chat blocked list
func (m *LolChatBlockedList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBlocked(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolChatBlockedList) validateBlocked(formats strfmt.Registry) error {

	if swag.IsZero(m.Blocked) { // not required
		return nil
	}

	for i := 0; i < len(m.Blocked); i++ {
		if swag.IsZero(m.Blocked[i]) { // not required
			continue
		}

		if m.Blocked[i] != nil {
			if err := m.Blocked[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("blocked" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolChatBlockedList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolChatBlockedList) UnmarshalBinary(b []byte) error {
	var res LolChatBlockedList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
