// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolRankedQueuesAndPuuidsPayload lol ranked queues and puuids payload
// swagger:model LolRankedQueuesAndPuuidsPayload
type LolRankedQueuesAndPuuidsPayload struct {

	// queue types
	QueueTypes []LolRankedLeagueQueueType `json:"queueTypes"`

	// summoner ids
	SummonerIds []int64 `json:"summonerIds"`
}

// Validate validates this lol ranked queues and puuids payload
func (m *LolRankedQueuesAndPuuidsPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQueueTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolRankedQueuesAndPuuidsPayload) validateQueueTypes(formats strfmt.Registry) error {

	if swag.IsZero(m.QueueTypes) { // not required
		return nil
	}

	for i := 0; i < len(m.QueueTypes); i++ {

		if err := m.QueueTypes[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("queueTypes" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolRankedQueuesAndPuuidsPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolRankedQueuesAndPuuidsPayload) UnmarshalBinary(b []byte) error {
	var res LolRankedQueuesAndPuuidsPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
