// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolStoreWallet lol store wallet
// swagger:model LolStoreWallet
type LolStoreWallet struct {

	// ip
	IP int64 `json:"ip,omitempty"`

	// rp
	Rp int64 `json:"rp,omitempty"`
}

// Validate validates this lol store wallet
func (m *LolStoreWallet) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolStoreWallet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolStoreWallet) UnmarshalBinary(b []byte) error {
	var res LolStoreWallet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
