// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolStoreItemCost lol store item cost
// swagger:model LolStoreItemCost
type LolStoreItemCost struct {

	// cost
	Cost int64 `json:"cost,omitempty"`

	// currency
	Currency string `json:"currency,omitempty"`

	// discount
	Discount float32 `json:"discount,omitempty"`
}

// Validate validates this lol store item cost
func (m *LolStoreItemCost) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolStoreItemCost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolStoreItemCost) UnmarshalBinary(b []byte) error {
	var res LolStoreItemCost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
