// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolCollectionsGameDataChampionMasteryGroup lol collections game data champion mastery group
// swagger:model LolCollectionsGameDataChampionMasteryGroup
type LolCollectionsGameDataChampionMasteryGroup struct {

	// id
	ID int32 `json:"id,omitempty"`

	// rows
	Rows []*LolCollectionsGameDataChampionMasteryRow `json:"rows"`
}

// Validate validates this lol collections game data champion mastery group
func (m *LolCollectionsGameDataChampionMasteryGroup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRows(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolCollectionsGameDataChampionMasteryGroup) validateRows(formats strfmt.Registry) error {

	if swag.IsZero(m.Rows) { // not required
		return nil
	}

	for i := 0; i < len(m.Rows); i++ {
		if swag.IsZero(m.Rows[i]) { // not required
			continue
		}

		if m.Rows[i] != nil {
			if err := m.Rows[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("rows" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolCollectionsGameDataChampionMasteryGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolCollectionsGameDataChampionMasteryGroup) UnmarshalBinary(b []byte) error {
	var res LolCollectionsGameDataChampionMasteryGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
