// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolChatUserResource lol chat user resource
// swagger:model LolChatUserResource
type LolChatUserResource struct {

	// availability
	Availability string `json:"availability,omitempty"`

	// basic
	Basic string `json:"basic,omitempty"`

	// game name
	GameName string `json:"gameName,omitempty"`

	// game tag
	GameTag string `json:"gameTag,omitempty"`

	// icon
	Icon int32 `json:"icon,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// last seen online timestamp
	LastSeenOnlineTimestamp string `json:"lastSeenOnlineTimestamp,omitempty"`

	// lol
	Lol map[string]string `json:"lol,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// patchline
	Patchline string `json:"patchline,omitempty"`

	// pid
	Pid string `json:"pid,omitempty"`

	// platform Id
	PlatformID string `json:"platformId,omitempty"`

	// product
	Product string `json:"product,omitempty"`

	// product name
	ProductName string `json:"productName,omitempty"`

	// status message
	StatusMessage string `json:"statusMessage,omitempty"`

	// summary
	Summary string `json:"summary,omitempty"`

	// summoner Id
	SummonerID int64 `json:"summonerId,omitempty"`

	// time
	Time int64 `json:"time,omitempty"`
}

// Validate validates this lol chat user resource
func (m *LolChatUserResource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolChatUserResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolChatUserResource) UnmarshalBinary(b []byte) error {
	var res LolChatUserResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
