// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolRecommendationsMatchHistoryList lol recommendations match history list
// swagger:model LolRecommendationsMatchHistoryList
type LolRecommendationsMatchHistoryList struct {

	// account Id
	AccountID int64 `json:"accountId,omitempty"`

	// games
	Games *LolRecommendationsMatchHistoryGameList `json:"games,omitempty"`

	// platform Id
	PlatformID string `json:"platformId,omitempty"`
}

// Validate validates this lol recommendations match history list
func (m *LolRecommendationsMatchHistoryList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGames(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolRecommendationsMatchHistoryList) validateGames(formats strfmt.Registry) error {

	if swag.IsZero(m.Games) { // not required
		return nil
	}

	if m.Games != nil {
		if err := m.Games.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("games")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolRecommendationsMatchHistoryList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolRecommendationsMatchHistoryList) UnmarshalBinary(b []byte) error {
	var res LolRecommendationsMatchHistoryList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
