// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolLobbyTeamBuilderChampSelectChatRoomDetails lol lobby team builder champ select chat room details
// swagger:model LolLobbyTeamBuilderChampSelectChatRoomDetails
type LolLobbyTeamBuilderChampSelectChatRoomDetails struct {

	// chat room name
	ChatRoomName string `json:"chatRoomName,omitempty"`

	// chat room password
	ChatRoomPassword string `json:"chatRoomPassword,omitempty"`
}

// Validate validates this lol lobby team builder champ select chat room details
func (m *LolLobbyTeamBuilderChampSelectChatRoomDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolLobbyTeamBuilderChampSelectChatRoomDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolLobbyTeamBuilderChampSelectChatRoomDetails) UnmarshalBinary(b []byte) error {
	var res LolLobbyTeamBuilderChampSelectChatRoomDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
