// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolPlayerMessagingPlayerMessagingNotificationResource lol player messaging player messaging notification resource
// swagger:model LolPlayerMessagingPlayerMessagingNotificationResource
type LolPlayerMessagingPlayerMessagingNotificationResource struct {

	// body
	Body string `json:"body,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// msg Id
	MsgID string `json:"msgId,omitempty"`

	// status
	Status int32 `json:"status,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this lol player messaging player messaging notification resource
func (m *LolPlayerMessagingPlayerMessagingNotificationResource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolPlayerMessagingPlayerMessagingNotificationResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolPlayerMessagingPlayerMessagingNotificationResource) UnmarshalBinary(b []byte) error {
	var res LolPlayerMessagingPlayerMessagingNotificationResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
