// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolRsoAuthPublicClientConfig lol rso auth public client config
// swagger:model LolRsoAuthPublicClientConfig
type LolRsoAuthPublicClientConfig struct {

	// client Id
	ClientID string `json:"clientId,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this lol rso auth public client config
func (m *LolRsoAuthPublicClientConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolRsoAuthPublicClientConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolRsoAuthPublicClientConfig) UnmarshalBinary(b []byte) error {
	var res LolRsoAuthPublicClientConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
