// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// LolLootLootType lol loot loot type
// swagger:model LolLootLootType
type LolLootLootType string

const (

	// LolLootLootTypeChest captures enum value "Chest"
	LolLootLootTypeChest LolLootLootType = "Chest"

	// LolLootLootTypeCurrency captures enum value "Currency"
	LolLootLootTypeCurrency LolLootLootType = "Currency"

	// LolLootLootTypeMaterial captures enum value "Material"
	LolLootLootTypeMaterial LolLootLootType = "Material"

	// LolLootLootTypeSkin captures enum value "Skin"
	LolLootLootTypeSkin LolLootLootType = "Skin"

	// LolLootLootTypeSkinRental captures enum value "Skin_Rental"
	LolLootLootTypeSkinRental LolLootLootType = "Skin_Rental"

	// LolLootLootTypeSummonerIcon captures enum value "SummonerIcon"
	LolLootLootTypeSummonerIcon LolLootLootType = "SummonerIcon"

	// LolLootLootTypeCompanion captures enum value "Companion"
	LolLootLootTypeCompanion LolLootLootType = "Companion"

	// LolLootLootTypeEgg captures enum value "Egg"
	LolLootLootTypeEgg LolLootLootType = "Egg"

	// LolLootLootTypeEggColor captures enum value "Egg_Color"
	LolLootLootTypeEggColor LolLootLootType = "Egg_Color"
)

// for schema
var lolLootLootTypeEnum []interface{}

func init() {
	var res []LolLootLootType
	if err := json.Unmarshal([]byte(`["Chest","Currency","Material","Skin","Skin_Rental","SummonerIcon","Companion","Egg","Egg_Color"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		lolLootLootTypeEnum = append(lolLootLootTypeEnum, v)
	}
}

func (m LolLootLootType) validateLolLootLootTypeEnum(path, location string, value LolLootLootType) error {
	if err := validate.Enum(path, location, value, lolLootLootTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this lol loot loot type
func (m LolLootLootType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateLolLootLootTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
