// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolLobbyQueueCustomGame lol lobby queue custom game
// swagger:model LolLobbyQueueCustomGame
type LolLobbyQueueCustomGame struct {

	// queue availability
	QueueAvailability LolLobbyQueueAvailability `json:"queueAvailability,omitempty"`
}

// Validate validates this lol lobby queue custom game
func (m *LolLobbyQueueCustomGame) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQueueAvailability(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolLobbyQueueCustomGame) validateQueueAvailability(formats strfmt.Registry) error {

	if swag.IsZero(m.QueueAvailability) { // not required
		return nil
	}

	if err := m.QueueAvailability.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("queueAvailability")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolLobbyQueueCustomGame) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolLobbyQueueCustomGame) UnmarshalBinary(b []byte) error {
	var res LolLobbyQueueCustomGame
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
