// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolMatchHistoryMatchHistoryParticipantIdentities lol match history match history participant identities
// swagger:model LolMatchHistoryMatchHistoryParticipantIdentities
type LolMatchHistoryMatchHistoryParticipantIdentities struct {

	// participant Id
	ParticipantID int64 `json:"participantId,omitempty"`

	// player
	Player *LolMatchHistoryMatchHistoryParticipantIdentityPlayer `json:"player,omitempty"`
}

// Validate validates this lol match history match history participant identities
func (m *LolMatchHistoryMatchHistoryParticipantIdentities) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlayer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolMatchHistoryMatchHistoryParticipantIdentities) validatePlayer(formats strfmt.Registry) error {

	if swag.IsZero(m.Player) { // not required
		return nil
	}

	if m.Player != nil {
		if err := m.Player.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("player")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolMatchHistoryMatchHistoryParticipantIdentities) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolMatchHistoryMatchHistoryParticipantIdentities) UnmarshalBinary(b []byte) error {
	var res LolMatchHistoryMatchHistoryParticipantIdentities
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
