// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolNpeRewardsLoginSeriesSettings lol npe rewards login series settings
// swagger:model LolNpeRewardsLoginSeriesSettings
type LolNpeRewardsLoginSeriesSettings struct {

	// all rewards claimed
	AllRewardsClaimed bool `json:"allRewardsClaimed,omitempty"`

	// last completed mission date
	LastCompletedMissionDate int64 `json:"lastCompletedMissionDate,omitempty"`

	// last completed mission internal name
	LastCompletedMissionInternalName string `json:"lastCompletedMissionInternalName,omitempty"`
}

// Validate validates this lol npe rewards login series settings
func (m *LolNpeRewardsLoginSeriesSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolNpeRewardsLoginSeriesSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolNpeRewardsLoginSeriesSettings) UnmarshalBinary(b []byte) error {
	var res LolNpeRewardsLoginSeriesSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
