// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// LolLobbyLobbyBotDifficulty lol lobby lobby bot difficulty
// swagger:model LolLobbyLobbyBotDifficulty
type LolLobbyLobbyBotDifficulty string

const (

	// LolLobbyLobbyBotDifficultyNONE captures enum value "NONE"
	LolLobbyLobbyBotDifficultyNONE LolLobbyLobbyBotDifficulty = "NONE"

	// LolLobbyLobbyBotDifficultyEASY captures enum value "EASY"
	LolLobbyLobbyBotDifficultyEASY LolLobbyLobbyBotDifficulty = "EASY"

	// LolLobbyLobbyBotDifficultyMEDIUM captures enum value "MEDIUM"
	LolLobbyLobbyBotDifficultyMEDIUM LolLobbyLobbyBotDifficulty = "MEDIUM"

	// LolLobbyLobbyBotDifficultyHARD captures enum value "HARD"
	LolLobbyLobbyBotDifficultyHARD LolLobbyLobbyBotDifficulty = "HARD"

	// LolLobbyLobbyBotDifficultyUBER captures enum value "UBER"
	LolLobbyLobbyBotDifficultyUBER LolLobbyLobbyBotDifficulty = "UBER"

	// LolLobbyLobbyBotDifficultyTUTORIAL captures enum value "TUTORIAL"
	LolLobbyLobbyBotDifficultyTUTORIAL LolLobbyLobbyBotDifficulty = "TUTORIAL"

	// LolLobbyLobbyBotDifficultyINTRO captures enum value "INTRO"
	LolLobbyLobbyBotDifficultyINTRO LolLobbyLobbyBotDifficulty = "INTRO"
)

// for schema
var lolLobbyLobbyBotDifficultyEnum []interface{}

func init() {
	var res []LolLobbyLobbyBotDifficulty
	if err := json.Unmarshal([]byte(`["NONE","EASY","MEDIUM","HARD","UBER","TUTORIAL","INTRO"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		lolLobbyLobbyBotDifficultyEnum = append(lolLobbyLobbyBotDifficultyEnum, v)
	}
}

func (m LolLobbyLobbyBotDifficulty) validateLolLobbyLobbyBotDifficultyEnum(path, location string, value LolLobbyLobbyBotDifficulty) error {
	if err := validate.Enum(path, location, value, lolLobbyLobbyBotDifficultyEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this lol lobby lobby bot difficulty
func (m LolLobbyLobbyBotDifficulty) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateLolLobbyLobbyBotDifficultyEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
