// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolLobbyGatekeeperRestrictionDto lol lobby gatekeeper restriction dto
// swagger:model LolLobbyGatekeeperRestrictionDto
type LolLobbyGatekeeperRestrictionDto struct {

	// account Id
	AccountID int64 `json:"accountId,omitempty"`

	// details
	Details map[string]string `json:"details,omitempty"`

	// payload
	Payload string `json:"payload,omitempty"`

	// puuid
	Puuid string `json:"puuid,omitempty"`

	// queue Id
	QueueID int32 `json:"queueId,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// remaining millis
	RemainingMillis int64 `json:"remainingMillis,omitempty"`
}

// Validate validates this lol lobby gatekeeper restriction dto
func (m *LolLobbyGatekeeperRestrictionDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolLobbyGatekeeperRestrictionDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolLobbyGatekeeperRestrictionDto) UnmarshalBinary(b []byte) error {
	var res LolLobbyGatekeeperRestrictionDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
