// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolPersonalizedOffersUIStatus lol personalized offers UI status
// swagger:model LolPersonalizedOffersUIStatus
type LolPersonalizedOffersUIStatus struct {

	// end time
	EndTime string `json:"endTime,omitempty"`

	// hub enabled
	HubEnabled bool `json:"hubEnabled,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// start time
	StartTime string `json:"startTime,omitempty"`
}

// Validate validates this lol personalized offers UI status
func (m *LolPersonalizedOffersUIStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolPersonalizedOffersUIStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolPersonalizedOffersUIStatus) UnmarshalBinary(b []byte) error {
	var res LolPersonalizedOffersUIStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
