// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolEndOfGameRerollDataBagForClientV1 lol end of game reroll data bag for client v1
// swagger:model LolEndOfGameRerollDataBagForClientV1
type LolEndOfGameRerollDataBagForClientV1 struct {

	// maximum rerolls
	MaximumRerolls int32 `json:"maximumRerolls,omitempty"`

	// point cost of reroll
	PointCostOfReroll int32 `json:"pointCostOfReroll,omitempty"`

	// points gained last game
	PointsGainedLastGame int32 `json:"pointsGainedLastGame,omitempty"`

	// points until next reroll
	PointsUntilNextReroll int32 `json:"pointsUntilNextReroll,omitempty"`

	// reroll count
	RerollCount int32 `json:"rerollCount,omitempty"`

	// total points
	TotalPoints int32 `json:"totalPoints,omitempty"`
}

// Validate validates this lol end of game reroll data bag for client v1
func (m *LolEndOfGameRerollDataBagForClientV1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolEndOfGameRerollDataBagForClientV1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolEndOfGameRerollDataBagForClientV1) UnmarshalBinary(b []byte) error {
	var res LolEndOfGameRerollDataBagForClientV1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
