// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolLobbyCollectionsChampionMinimal lol lobby collections champion minimal
// swagger:model LolLobbyCollectionsChampionMinimal
type LolLobbyCollectionsChampionMinimal struct {

	// active
	Active bool `json:"active,omitempty"`

	// disabled queues
	DisabledQueues []string `json:"disabledQueues"`

	// free to play
	FreeToPlay bool `json:"freeToPlay,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// ownership
	Ownership *LolLobbyCollectionsOwnership `json:"ownership,omitempty"`
}

// Validate validates this lol lobby collections champion minimal
func (m *LolLobbyCollectionsChampionMinimal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOwnership(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolLobbyCollectionsChampionMinimal) validateOwnership(formats strfmt.Registry) error {

	if swag.IsZero(m.Ownership) { // not required
		return nil
	}

	if m.Ownership != nil {
		if err := m.Ownership.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ownership")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolLobbyCollectionsChampionMinimal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolLobbyCollectionsChampionMinimal) UnmarshalBinary(b []byte) error {
	var res LolLobbyCollectionsChampionMinimal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
