// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LolStatstonesStatstoneVignetteNotificationEnvelopeDto lol statstones statstone vignette notification envelope dto
// swagger:model LolStatstonesStatstoneVignetteNotificationEnvelopeDto
type LolStatstonesStatstoneVignetteNotificationEnvelopeDto struct {

	// champ Id
	ChampID int32 `json:"champId,omitempty"`

	// champ name
	ChampName string `json:"champName,omitempty"`

	// mastery vignette notifications
	MasteryVignetteNotifications []*LolStatstonesStatstoneMasteryVignette `json:"masteryVignetteNotifications"`

	// rekindled vignette notifications
	RekindledVignetteNotifications []*LolStatstonesStatstoneRekindledVignette `json:"rekindledVignetteNotifications"`

	// set complete vignette notifications
	SetCompleteVignetteNotifications []*LolStatstonesStatstoneSetCompleteVignette `json:"setCompleteVignetteNotifications"`
}

// Validate validates this lol statstones statstone vignette notification envelope dto
func (m *LolStatstonesStatstoneVignetteNotificationEnvelopeDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMasteryVignetteNotifications(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRekindledVignetteNotifications(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSetCompleteVignetteNotifications(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LolStatstonesStatstoneVignetteNotificationEnvelopeDto) validateMasteryVignetteNotifications(formats strfmt.Registry) error {

	if swag.IsZero(m.MasteryVignetteNotifications) { // not required
		return nil
	}

	for i := 0; i < len(m.MasteryVignetteNotifications); i++ {
		if swag.IsZero(m.MasteryVignetteNotifications[i]) { // not required
			continue
		}

		if m.MasteryVignetteNotifications[i] != nil {
			if err := m.MasteryVignetteNotifications[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("masteryVignetteNotifications" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LolStatstonesStatstoneVignetteNotificationEnvelopeDto) validateRekindledVignetteNotifications(formats strfmt.Registry) error {

	if swag.IsZero(m.RekindledVignetteNotifications) { // not required
		return nil
	}

	for i := 0; i < len(m.RekindledVignetteNotifications); i++ {
		if swag.IsZero(m.RekindledVignetteNotifications[i]) { // not required
			continue
		}

		if m.RekindledVignetteNotifications[i] != nil {
			if err := m.RekindledVignetteNotifications[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("rekindledVignetteNotifications" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LolStatstonesStatstoneVignetteNotificationEnvelopeDto) validateSetCompleteVignetteNotifications(formats strfmt.Registry) error {

	if swag.IsZero(m.SetCompleteVignetteNotifications) { // not required
		return nil
	}

	for i := 0; i < len(m.SetCompleteVignetteNotifications); i++ {
		if swag.IsZero(m.SetCompleteVignetteNotifications[i]) { // not required
			continue
		}

		if m.SetCompleteVignetteNotifications[i] != nil {
			if err := m.SetCompleteVignetteNotifications[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("setCompleteVignetteNotifications" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LolStatstonesStatstoneVignetteNotificationEnvelopeDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolStatstonesStatstoneVignetteNotificationEnvelopeDto) UnmarshalBinary(b []byte) error {
	var res LolStatstonesStatstoneVignetteNotificationEnvelopeDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
