// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LolClashInviteSubRequest lol clash invite sub request
// swagger:model LolClashInviteSubRequest
type LolClashInviteSubRequest struct {

	// replaced summoner Id
	ReplacedSummonerID int64 `json:"replacedSummonerId,omitempty"`

	// substitute summoner Id
	SubstituteSummonerID int64 `json:"substituteSummonerId,omitempty"`
}

// Validate validates this lol clash invite sub request
func (m *LolClashInviteSubRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LolClashInviteSubRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LolClashInviteSubRequest) UnmarshalBinary(b []byte) error {
	var res LolClashInviteSubRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
