// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PaymentsPMCStartURLRequest payments p m c start Url request
// swagger:model PaymentsPMCStartUrlRequest
type PaymentsPMCStartURLRequest struct {

	// giftee account Id
	GifteeAccountID string `json:"gifteeAccountId,omitempty"`

	// giftee message
	GifteeMessage string `json:"gifteeMessage,omitempty"`

	// is prepaid
	IsPrepaid bool `json:"isPrepaid,omitempty"`

	// locale Id
	LocaleID string `json:"localeId,omitempty"`

	// summoner level
	SummonerLevel int64 `json:"summonerLevel,omitempty"`
}

// Validate validates this payments p m c start Url request
func (m *PaymentsPMCStartURLRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentsPMCStartURLRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentsPMCStartURLRequest) UnmarshalBinary(b []byte) error {
	var res PaymentsPMCStartURLRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
