// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PlayerMissionRewardDTO player mission reward d t o
// swagger:model PlayerMissionRewardDTO
type PlayerMissionRewardDTO struct {

	// description
	Description string `json:"description,omitempty"`

	// icon Url
	IconURL string `json:"iconUrl,omitempty"`

	// is objective based reward
	IsObjectiveBasedReward bool `json:"isObjectiveBasedReward,omitempty"`

	// item Id
	ItemID string `json:"itemId,omitempty"`

	// quantity
	Quantity int32 `json:"quantity,omitempty"`

	// reward fulfilled
	RewardFulfilled bool `json:"rewardFulfilled,omitempty"`

	// reward group
	RewardGroup string `json:"rewardGroup,omitempty"`

	// reward group selected
	RewardGroupSelected bool `json:"rewardGroupSelected,omitempty"`

	// reward type
	RewardType string `json:"rewardType,omitempty"`

	// sequence
	Sequence int32 `json:"sequence,omitempty"`

	// unique name
	UniqueName string `json:"uniqueName,omitempty"`
}

// Validate validates this player mission reward d t o
func (m *PlayerMissionRewardDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlayerMissionRewardDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlayerMissionRewardDTO) UnmarshalBinary(b []byte) error {
	var res PlayerMissionRewardDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
