// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RankedQueueWarningsDTO ranked queue warnings d t o
// swagger:model RankedQueueWarningsDTO
type RankedQueueWarningsDTO struct {

	// apex days until decay
	ApexDaysUntilDecay int32 `json:"apexDaysUntilDecay,omitempty"`

	// demotion warning
	DemotionWarning int32 `json:"demotionWarning,omitempty"`

	// display decay warning
	DisplayDecayWarning bool `json:"displayDecayWarning,omitempty"`

	// time until inactivity status changes
	TimeUntilInactivityStatusChanges int64 `json:"timeUntilInactivityStatusChanges,omitempty"`
}

// Validate validates this ranked queue warnings d t o
func (m *RankedQueueWarningsDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RankedQueueWarningsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RankedQueueWarningsDTO) UnmarshalBinary(b []byte) error {
	var res RankedQueueWarningsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
