// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SplitRewardGrantDTO split reward grant d t o
// swagger:model SplitRewardGrantDTO
type SplitRewardGrantDTO struct {

	// reward Id
	RewardID string `json:"rewardId,omitempty"`

	// reward type
	RewardType string `json:"rewardType,omitempty"`
}

// Validate validates this split reward grant d t o
func (m *SplitRewardGrantDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SplitRewardGrantDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SplitRewardGrantDTO) UnmarshalBinary(b []byte) error {
	var res SplitRewardGrantDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
